# Generated by Django 5.1.6 on 2026-01-06 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluations', '0003_remove_solution_question_alter_evaluation_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='mode_correction',
            field=models.CharField(choices=[('automatique', 'Correction automatique'), ('manuelle', 'Correction manuelle')], default='automatique', editable=False, max_length=20),
        ),
    ]
