# Generated by Django 5.1.6 on 2026-01-06 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluations', '0004_alter_question_mode_correction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='mode_correction',
            field=models.CharField(choices=[('automatique', 'Correction automatique'), ('manuelle', 'Correction manuelle')], default='automatique', max_length=20),
        ),
    ]
