# Generated by Django 5.1.6 on 2026-02-09 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluations', '0005_alter_question_mode_correction'),
    ]

    operations = [
        migrations.AddField(
            model_name='reponsequestion',
            name='date_modification',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
