# Generated by Django 5.1.6 on 2026-02-12 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('evaluations', '0006_alter_evaluation_consigne_texte_and_more'),
        ('evaluations', '0006_reponsequestion_date_modification'),
    ]

    operations = [
    ]
