# Generated by Django 5.1.6 on 2026-04-21 23:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluations', '0007_merge_20260212_1727'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='fichier_enonce',
            field=models.FileField(blank=True, help_text="Fichier annexe à l'énoncé (image, document...)", null=True, upload_to='uploads/questions/enonces/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'docx', 'doc', 'jpg', 'jpeg', 'png', 'gif'])]),
        ),
    ]
