# Generated by Django 5.2.12 on 2026-04-21 23:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluations', '0008_alter_question_fichier_enonce'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reponsequestion',
            name='fichier_reponse',
            field=models.FileField(blank=True, help_text="Fichier réponse de l'apprenant", null=True, upload_to='uploads/questions/reponses/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'docx', 'doc', 'txt', 'zip', 'jpg', 'jpeg', 'png'])]),
        ),
    ]
