# Generated by Django 5.1.6 on 2026-01-07 17:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0005_cours_titre'),
        ('evaluations', '0005_alter_question_mode_correction'),
        ('users', '0023_remove_apprenant_classe'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_echeance', models.DateField(blank=True, null=True)),
                ('date_completion', models.DateTimeField(blank=True, null=True)),
                ('statut', models.CharField(choices=[('a_faire', 'À faire'), ('en_cours', 'En cours'), ('termine', 'Terminé'), ('annule', 'Annulé')], default='a_faire', max_length=20)),
                ('priorite', models.CharField(choices=[('basse', 'Basse'), ('moyenne', 'Moyenne'), ('haute', 'Haute'), ('urgente', 'Urgente')], default='moyenne', max_length=20)),
                ('apprenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plans_action', to='users.apprenant')),
                ('cours', models.ForeignKey(blank=True, help_text='Cours associé (optionnel)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='plans_action', to='courses.cours')),
                ('cree_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='plans_action_crees', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': "Plan d'action",
                'verbose_name_plural': "Plans d'action",
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='ObjectifPlanAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('est_complete', models.BooleanField(default=False)),
                ('date_completion', models.DateTimeField(blank=True, null=True)),
                ('ordre', models.PositiveIntegerField(default=0)),
                ('plan_action', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='objectifs', to='progress.planaction')),
            ],
            options={
                'verbose_name': "Objectif de plan d'action",
                'verbose_name_plural': "Objectifs de plans d'action",
                'ordering': ['ordre'],
            },
        ),
        migrations.CreateModel(
            name='ProgressionApprenant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_debut', models.DateTimeField(auto_now_add=True)),
                ('date_derniere_activite', models.DateTimeField(auto_now=True)),
                ('date_completion', models.DateTimeField(blank=True, null=True)),
                ('pourcentage_completion', models.FloatField(default=0.0, help_text='Pourcentage de completion du cours (0-100)')),
                ('temps_total_minutes', models.IntegerField(default=0, help_text='Temps total passé sur le cours en minutes')),
                ('statut', models.CharField(choices=[('non_commence', 'Non commencé'), ('en_cours', 'En cours'), ('termine', 'Terminé'), ('abandonne', 'Abandonné'), ('suspendu', 'Suspendu')], default='non_commence', max_length=20)),
                ('note_moyenne_evaluations', models.FloatField(blank=True, help_text='Note moyenne sur toutes les évaluations du cours', null=True)),
                ('taux_reussite_quiz', models.FloatField(default=0.0, help_text='Taux de réussite moyen sur les quiz')),
                ('apprenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progressions_cours', to='users.apprenant')),
                ('cours', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progressions_apprenants', to='courses.cours')),
                ('dernier_module', models.ForeignKey(blank=True, help_text='Dernier module consulté', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='progressions_en_cours', to='courses.module')),
                ('derniere_sequence', models.ForeignKey(blank=True, help_text='Dernière séquence consultée', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='progressions_en_cours', to='courses.sequence')),
            ],
            options={
                'verbose_name': "Progression de l'apprenant",
                'verbose_name_plural': 'Progressions des apprenants',
                'ordering': ['-date_derniere_activite'],
            },
        ),
        migrations.CreateModel(
            name='ProgressionModule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_debut', models.DateTimeField(auto_now_add=True)),
                ('date_fin', models.DateTimeField(blank=True, null=True)),
                ('temps_passe_minutes', models.IntegerField(default=0)),
                ('est_termine', models.BooleanField(default=False)),
                ('pourcentage_completion', models.FloatField(default=0.0)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progressions', to='courses.module')),
                ('progression_apprenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progressions_modules', to='progress.progressionapprenant')),
            ],
            options={
                'verbose_name': 'Progression dans un module',
                'verbose_name_plural': 'Progressions dans les modules',
                'ordering': ['module__id'],
            },
        ),
        migrations.CreateModel(
            name='ProgressionQuiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_passage', models.DateTimeField(auto_now_add=True)),
                ('score', models.FloatField(default=0.0)),
                ('temps_passe_minutes', models.IntegerField(default=0)),
                ('pourcentage_reussite', models.FloatField(default=0.0)),
                ('numero_tentative', models.IntegerField(default=1)),
                ('passage_quiz', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='progression', to='evaluations.passagequiz')),
                ('progression_apprenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progressions_quiz', to='progress.progressionapprenant')),
            ],
            options={
                'verbose_name': 'Progression dans un quiz',
                'verbose_name_plural': 'Progressions dans les quiz',
                'ordering': ['-date_passage'],
            },
        ),
        migrations.CreateModel(
            name='ProgressionSequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_debut', models.DateTimeField(auto_now_add=True)),
                ('date_fin', models.DateTimeField(blank=True, null=True)),
                ('temps_passe_minutes', models.IntegerField(default=0)),
                ('est_terminee', models.BooleanField(default=False)),
                ('pourcentage_completion', models.FloatField(default=0.0)),
                ('nombre_visites', models.IntegerField(default=0)),
                ('progression_module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progressions_sequences', to='progress.progressionmodule')),
                ('sequence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progressions', to='courses.sequence')),
            ],
            options={
                'verbose_name': 'Progression dans une séquence',
                'verbose_name_plural': 'Progressions dans les séquences',
                'ordering': ['sequence__id'],
            },
        ),
        migrations.CreateModel(
            name='HistoriqueActivite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_activite', models.CharField(choices=[('connexion', 'Connexion'), ('deconnexion', 'Déconnexion'), ('consultation_cours', 'Consultation de cours'), ('consultation_module', 'Consultation de module'), ('consultation_sequence', 'Consultation de séquence'), ('debut_quiz', 'Début de quiz'), ('fin_quiz', 'Fin de quiz'), ('debut_evaluation', "Début d'évaluation"), ('soumission_evaluation', "Soumission d'évaluation"), ('telechargement_ressource', 'Téléchargement de ressource'), ('participation_session', 'Participation à une session'), ('autre', 'Autre activité')], max_length=50)),
                ('objet_type', models.CharField(blank=True, help_text="Type d'objet concerné (cours, quiz, etc.)", max_length=50)),
                ('objet_id', models.IntegerField(blank=True, help_text="ID de l'objet concerné", null=True)),
                ('date_activite', models.DateTimeField(auto_now_add=True)),
                ('duree_minutes', models.IntegerField(default=0, help_text="Durée de l'activité en minutes")),
                ('description', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Métadonnées supplémentaires')),
                ('apprenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historique_activites', to='users.apprenant')),
            ],
            options={
                'verbose_name': "Historique d'activité",
                'verbose_name_plural': "Historiques d'activités",
                'ordering': ['-date_activite'],
                'indexes': [models.Index(fields=['apprenant', '-date_activite'], name='progress_hi_apprena_317b54_idx'), models.Index(fields=['type_activite'], name='progress_hi_type_ac_71c857_idx'), models.Index(fields=['objet_type', 'objet_id'], name='progress_hi_objet_t_4c2ce1_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='progressionapprenant',
            index=models.Index(fields=['apprenant', 'cours'], name='progress_pr_apprena_c2ac60_idx'),
        ),
        migrations.AddIndex(
            model_name='progressionapprenant',
            index=models.Index(fields=['statut'], name='progress_pr_statut_f2eff1_idx'),
        ),
        migrations.AddIndex(
            model_name='progressionapprenant',
            index=models.Index(fields=['-date_derniere_activite'], name='progress_pr_date_de_542555_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='progressionapprenant',
            unique_together={('apprenant', 'cours')},
        ),
        migrations.AlterUniqueTogether(
            name='progressionmodule',
            unique_together={('progression_apprenant', 'module')},
        ),
        migrations.AlterUniqueTogether(
            name='progressionsequence',
            unique_together={('progression_module', 'sequence')},
        ),
    ]
