# Generated by Django 5.1.2 on 2024-11-18 00:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0003_anneescolaire_description_classe_date_creation_and_more'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formateur',
            name='telephone',
        ),
        migrations.AddField(
            model_name='admin',
            name='date_entree',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='apprenant',
            name='date_naissance',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='apprenant',
            name='matricule',
            field=models.CharField(max_length=20, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='parent',
            name='institution',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parents', to='academics.institution'),
        ),
        migrations.AddField(
            model_name='responsableacademique',
            name='departement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='responsables_departement', to='academics.departement'),
        ),
        migrations.AddField(
            model_name='user',
            name='telephone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
