# Generated by Django 5.1.2 on 2024-12-08 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0003_anneescolaire_description_classe_date_creation_and_more'),
        ('users', '0007_alter_user_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formateur',
            name='groupes',
            field=models.ManyToManyField(blank=True, null=True, related_name='formateurs', to='academics.groupe'),
        ),
        migrations.AlterField(
            model_name='formateur',
            name='institutions',
            field=models.ManyToManyField(blank=True, null=True, related_name='formateurs_users', to='academics.institution'),
        ),
        migrations.AlterField(
            model_name='formateur',
            name='specialites',
            field=models.ManyToManyField(blank=True, null=True, related_name='formateurs', to='academics.specialite'),
        ),
    ]
