# Generated by Django 5.1.2 on 2024-12-08 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_formateur_groupes_alter_formateur_institutions_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='activation_token',
            field=models.CharField(blank=True, editable=False, max_length=255),
        ),
    ]
