# Generated by Django 5.0.12 on 2025-02-21 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0003_anneescolaire_description_classe_date_creation_and_more'),
        ('users', '0009_user_activation_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formateur',
            name='groupes',
            field=models.ManyToManyField(blank=True, related_name='formateurs', to='academics.groupe'),
        ),
        migrations.AlterField(
            model_name='formateur',
            name='institutions',
            field=models.ManyToManyField(blank=True, related_name='formateurs_users', to='academics.institution'),
        ),
        migrations.AlterField(
            model_name='formateur',
            name='specialites',
            field=models.ManyToManyField(blank=True, related_name='formateurs', to='academics.specialite'),
        ),
    ]
