# Generated by Django 5.1.6 on 2025-03-24 22:55

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_userrole_admin_user_apprenant_user_formateur_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='activation_token',
            field=models.UUIDField(blank=True, default=uuid.uuid4, editable=False),
        ),
    ]
