# Generated by Django 5.1.6 on 2025-03-24 23:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_alter_user_activation_token'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='activation_token',
        ),
    ]
