# Generated by Django 5.1.6 on 2025-03-25 00:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_alter_user_activation_token'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='admin',
            name='user',
        ),
        migrations.RemoveField(
            model_name='apprenant',
            name='user',
        ),
        migrations.RemoveField(
            model_name='formateur',
            name='user',
        ),
        migrations.RemoveField(
            model_name='parent',
            name='user',
        ),
        migrations.RemoveField(
            model_name='responsableacademique',
            name='user',
        ),
    ]
