# Generated by Django 5.1.6 on 2025-03-25 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0003_anneescolaire_description_classe_date_creation_and_more'),
        ('users', '0018_alter_formateur_groupes_alter_formateur_institutions_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formateur',
            name='groupes',
            field=models.ManyToManyField(blank=True, related_name='formateurs', to='academics.groupe'),
        ),
        migrations.AlterField(
            model_name='formateur',
            name='institutions',
            field=models.ManyToManyField(blank=True, related_name='formateurs_users', to='academics.institution'),
        ),
        migrations.AlterField(
            model_name='formateur',
            name='specialites',
            field=models.ManyToManyField(blank=True, related_name='formateurs', to='academics.specialite'),
        ),
    ]
