# Generated by Django 5.1.6 on 2025-11-12 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_alter_formateur_groupes_alter_formateur_institutions_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin',
            name='date_entree',
            field=models.DateField(auto_now=True, null=True),
        ),
    ]
