# Generated by Django 5.1.6 on 2025-12-28 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0005_remove_institution_formateurs_and_more'),
        ('users', '0021_alter_admin_date_entree_alter_admin_institution_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formateur',
            name='institutions',
            field=models.ManyToManyField(blank=True, related_name='formateurs', to='academics.institution'),
        ),
    ]
