# Generated by Django 5.1.6 on 2025-12-28 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0022_alter_formateur_institutions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apprenant',
            name='classe',
        ),
    ]
