# Generated by Django 5.1.6 on 2026-02-11 11:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0007_remove_inscription_uniq_apprenant_par_annee_and_more'),
        ('users', '0023_remove_apprenant_classe'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='admin',
            name='institution',
        ),
        migrations.RemoveField(
            model_name='parent',
            name='institution',
        ),
        migrations.RemoveField(
            model_name='responsableacademique',
            name='institution',
        ),
        migrations.AddField(
            model_name='user',
            name='annee_scolaire_active',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users_actifs', to='academics.anneescolaire', verbose_name='Année scolaire active'),
        ),
        migrations.AddField(
            model_name='user',
            name='institution',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='academics.institution', verbose_name='Établissement'),
        ),
    ]
