# Generated by Django 5.1.6 on 2026-02-11 14:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0007_remove_inscription_uniq_apprenant_par_annee_and_more'),
        ('users', '0024_remove_admin_institution_remove_parent_institution_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='admin',
            options={'verbose_name': 'Administrateur', 'verbose_name_plural': 'Administrateurs'},
        ),
        migrations.AlterModelOptions(
            name='apprenant',
            options={'verbose_name': 'Apprenant', 'verbose_name_plural': 'Apprenants'},
        ),
        migrations.AlterModelOptions(
            name='formateur',
            options={'verbose_name': 'Formateur', 'verbose_name_plural': 'Formateurs'},
        ),
        migrations.AlterModelOptions(
            name='parent',
            options={'verbose_name': 'Parent', 'verbose_name_plural': 'Parents'},
        ),
        migrations.AlterModelOptions(
            name='responsableacademique',
            options={'verbose_name': 'Responsable académique', 'verbose_name_plural': 'Responsables académiques'},
        ),
        migrations.AlterModelOptions(
            name='superadmin',
            options={'verbose_name': 'Super administrateur', 'verbose_name_plural': 'Super administrateurs'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'Utilisateur', 'verbose_name_plural': 'Utilisateurs'},
        ),
        migrations.AlterField(
            model_name='user',
            name='annee_scolaire_active',
            field=models.ForeignKey(blank=True, help_text='Année scolaire actuellement consultée. DOIT être NULL pour les SuperUsers.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users_actifs', to='academics.anneescolaire', verbose_name='Année scolaire active'),
        ),
        migrations.AlterField(
            model_name='user',
            name='institution',
            field=models.ForeignKey(blank=True, help_text="Institution de l'utilisateur. DOIT être NULL pour les SuperUsers.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='academics.institution', verbose_name='Établissement'),
        ),
    ]
