# Generated by Django 5.1.6 on 2026-02-12 00:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0008_alter_domaineetude_options_alter_filiere_options_and_more'),
        ('users', '0025_alter_admin_options_alter_apprenant_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='admin',
            options={},
        ),
        migrations.AlterModelOptions(
            name='apprenant',
            options={},
        ),
        migrations.AlterModelOptions(
            name='formateur',
            options={},
        ),
        migrations.AlterModelOptions(
            name='parent',
            options={},
        ),
        migrations.AlterModelOptions(
            name='responsableacademique',
            options={},
        ),
        migrations.AlterModelOptions(
            name='superadmin',
            options={},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={},
        ),
        migrations.AlterField(
            model_name='user',
            name='annee_scolaire_active',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users_actifs', to='academics.anneescolaire', verbose_name='Année scolaire active'),
        ),
        migrations.AlterField(
            model_name='user',
            name='institution',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='academics.institution', verbose_name='Établissement'),
        ),
    ]
