# Generated by Django 5.1.6 on 2026-02-27 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0026_alter_admin_options_alter_apprenant_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='photos/profils/', verbose_name='Photo de profil'),
        ),
    ]
