# Generated by Django 5.1.6 on 2026-02-20 09:06

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0013_alter_participation_source'),
        ('users', '0026_alter_admin_options_alter_apprenant_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlocAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ouvert_le', models.DateTimeField(default=django.utils.timezone.now)),
                ('ferme_le', models.DateTimeField(blank=True, null=True)),
                ('duree_secondes', models.PositiveIntegerField(default=0)),
                ('scroll_max_pct', models.PositiveSmallIntegerField(default=0)),
                ('complete_en_session', models.BooleanField(default=False)),
                ('apprenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bloc_analytics', to='users.apprenant')),
                ('bloc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analytics_sessions', to='courses.bloccontenu')),
                ('cours', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='courses.cours')),
                ('module', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='courses.module')),
                ('sequence', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='courses.sequence')),
            ],
            options={
                'verbose_name': 'Session de bloc',
                'verbose_name_plural': 'Sessions de blocs',
                'ordering': ['-ouvert_le'],
                'indexes': [models.Index(fields=['apprenant', 'bloc'], name='analytics_b_apprena_98422f_idx'), models.Index(fields=['apprenant', 'cours'], name='analytics_b_apprena_8dac2f_idx')],
            },
        ),
        migrations.CreateModel(
            name='BlocAnalyticsSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nb_ouvertures', models.PositiveIntegerField(default=0)),
                ('nb_completions', models.PositiveIntegerField(default=0)),
                ('duree_totale_sec', models.PositiveIntegerField(default=0)),
                ('duree_moy_sec', models.PositiveIntegerField(default=0)),
                ('ratio_temps_pct', models.SmallIntegerField(default=0)),
                ('scroll_max_pct', models.PositiveSmallIntegerField(default=0)),
                ('premiere_ouverture', models.DateTimeField(blank=True, null=True)),
                ('derniere_ouverture', models.DateTimeField(blank=True, null=True)),
                ('date_completion', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('apprenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bloc_summaries', to='users.apprenant')),
                ('bloc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analytics_summary', to='courses.bloccontenu')),
                ('cours', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='courses.cours')),
                ('module', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='courses.module')),
                ('sequence', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='courses.sequence')),
            ],
            options={
                'verbose_name': 'Résumé bloc',
                'verbose_name_plural': 'Résumés blocs',
                'unique_together': {('apprenant', 'bloc')},
            },
        ),
        migrations.CreateModel(
            name='ModuleAnalyticsSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nb_sequences_consultees', models.PositiveSmallIntegerField(default=0)),
                ('nb_sequences_total', models.PositiveSmallIntegerField(default=0)),
                ('nb_sequences_completes', models.PositiveSmallIntegerField(default=0)),
                ('nb_blocs_total', models.PositiveSmallIntegerField(default=0)),
                ('nb_blocs_completes', models.PositiveSmallIntegerField(default=0)),
                ('duree_totale_sec', models.PositiveIntegerField(default=0)),
                ('duree_estimee_sec', models.PositiveIntegerField(default=0)),
                ('ratio_temps_pct', models.SmallIntegerField(default=0)),
                ('score_moyen_quiz', models.SmallIntegerField(default=0)),
                ('premiere_activite', models.DateTimeField(blank=True, null=True)),
                ('derniere_activite', models.DateTimeField(blank=True, null=True)),
                ('complete_le', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('apprenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='module_summaries', to='users.apprenant')),
                ('cours', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='courses.cours')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analytics_summary', to='courses.module')),
            ],
            options={
                'unique_together': {('apprenant', 'module')},
            },
        ),
        migrations.CreateModel(
            name='SequenceAnalyticsSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nb_blocs_consultes', models.PositiveSmallIntegerField(default=0)),
                ('nb_blocs_total', models.PositiveSmallIntegerField(default=0)),
                ('nb_blocs_completes', models.PositiveSmallIntegerField(default=0)),
                ('duree_totale_sec', models.PositiveIntegerField(default=0)),
                ('duree_estimee_sec', models.PositiveIntegerField(default=0)),
                ('ratio_temps_pct', models.SmallIntegerField(default=0)),
                ('nb_quiz_passes', models.PositiveSmallIntegerField(default=0)),
                ('score_moyen_quiz', models.SmallIntegerField(default=0)),
                ('premiere_activite', models.DateTimeField(blank=True, null=True)),
                ('derniere_activite', models.DateTimeField(blank=True, null=True)),
                ('completee_le', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('apprenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sequence_summaries', to='users.apprenant')),
                ('cours', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='courses.cours')),
                ('module', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='courses.module')),
                ('sequence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analytics_summary', to='courses.sequence')),
            ],
            options={
                'unique_together': {('apprenant', 'sequence')},
            },
        ),
    ]
