# Generated by Django 5.1.6 on 2026-02-10 11:36

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0008_coursprogress_moduleprogress_sequenceprogress_and_more'),
        ('evaluations', '0005_alter_question_mode_correction'),
        ('users', '0023_remove_apprenant_classe'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContenuGenere',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_generation', models.CharField(choices=[('remediation', 'Remédiation (après échec)'), ('approfondissement', 'Approfondissement'), ('simplification', 'Simplification'), ('alternative', 'Approche alternative')], max_length=20)),
                ('titre', models.CharField(max_length=255)),
                ('contenu_html', models.TextField()),
                ('contenu_markdown', models.TextField(blank=True, default='')),
                ('concepts_cibles', models.JSONField(blank=True, default=list, help_text="Ex: ['variables', 'types']")),
                ('niveau_difficulte', models.IntegerField(default=2, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('a_ete_consulte', models.BooleanField(default=False)),
                ('a_aide', models.BooleanField(blank=True, help_text='Feedback apprenant', null=True)),
                ('nombre_consultations', models.PositiveIntegerField(default=0)),
                ('date_generation', models.DateTimeField(auto_now_add=True)),
                ('date_derniere_consultation', models.DateTimeField(blank=True, null=True)),
                ('apprenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contenus_generes', to='users.apprenant')),
                ('bloc_source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contenus_generes', to='courses.bloccontenu')),
            ],
            options={
                'verbose_name': 'Contenu généré',
                'verbose_name_plural': 'Contenus générés',
                'ordering': ['-date_generation'],
            },
        ),
        migrations.CreateModel(
            name='BlocAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temps_total_secondes', models.PositiveIntegerField(default=0)),
                ('nombre_visites', models.PositiveIntegerField(default=0)),
                ('pourcentage_scroll', models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('interactions', models.JSONField(blank=True, default=dict)),
                ('score_comprehension', models.FloatField(blank=True, null=True)),
                ('difficulte_percue', models.IntegerField(blank=True, choices=[(1, 'Très facile'), (2, 'Facile'), (3, 'Moyen'), (4, 'Difficile'), (5, 'Très difficile')], null=True)),
                ('premiere_visite', models.DateTimeField(auto_now_add=True)),
                ('derniere_visite', models.DateTimeField(auto_now=True)),
                ('apprenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocs_analytics', to='users.apprenant')),
                ('bloc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analytics', to='courses.bloccontenu')),
            ],
            options={
                'verbose_name': 'Analytique de bloc',
                'verbose_name_plural': 'Analytiques de blocs',
                'indexes': [models.Index(fields=['apprenant', 'temps_total_secondes'], name='analytics_b_apprena_e38234_idx'), models.Index(fields=['bloc', 'score_comprehension'], name='analytics_b_bloc_id_68aaf9_idx')],
                'unique_together': {('apprenant', 'bloc')},
            },
        ),
        migrations.CreateModel(
            name='QuestionAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_tentatives', models.PositiveIntegerField(default=0)),
                ('nombre_echecs', models.PositiveIntegerField(default=0)),
                ('temps_moyen_reponse_sec', models.FloatField(default=0.0)),
                ('erreurs_frequentes', models.JSONField(blank=True, default=list, help_text='IDs des mauvaises réponses choisies')),
                ('concepts_fragiles', models.JSONField(blank=True, default=list, help_text="Ex: ['boucles', 'variables']")),
                ('derniere_tentative', models.DateTimeField(auto_now=True)),
                ('apprenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions_analytics', to='users.apprenant')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analytics', to='evaluations.question')),
            ],
            options={
                'verbose_name': 'Analytique de question',
                'verbose_name_plural': 'Analytiques de questions',
                'unique_together': {('apprenant', 'question')},
            },
        ),
        migrations.CreateModel(
            name='RecommandationPedagogique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_recommandation', models.CharField(choices=[('bloc_revoir', 'Revoir un bloc'), ('quiz_supplementaire', 'Quiz supplémentaire'), ('pause', 'Pause recommandée'), ('changement_approche', "Changer d'approche"), ('contenu_alternatif', 'Contenu alternatif disponible')], max_length=30)),
                ('message', models.TextField()),
                ('priorite', models.IntegerField(default=3, help_text='1=haute priorité, 5=basse priorité', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('est_vue', models.BooleanField(default=False)),
                ('est_suivie', models.BooleanField(default=False)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_vue', models.DateTimeField(blank=True, null=True)),
                ('date_expiration', models.DateTimeField(blank=True, null=True)),
                ('apprenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommandations', to='users.apprenant')),
                ('bloc_cible', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='courses.bloccontenu')),
                ('contenu_genere', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='analytics.contenugenere')),
            ],
            options={
                'verbose_name': 'Recommandation pédagogique',
                'verbose_name_plural': 'Recommandations pédagogiques',
                'ordering': ['priorite', '-date_creation'],
                'indexes': [models.Index(fields=['apprenant', 'est_vue', 'date_expiration'], name='analytics_r_apprena_804fb0_idx')],
            },
        ),
    ]
