# analytics/migrations/0002_ai_models.py
# Generated by Django 5.2.12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
        ('courses', '0013_alter_participation_source'),
        ('evaluations', '0007_merge_20260212_1727'),
        ('users', '0026_alter_admin_options_alter_apprenant_options_and_more'),
    ]

    operations = [

        # ── AIAnalysisRequest ────────────────────────────────────────────────
        migrations.CreateModel(
            name='AIAnalysisRequest',
            fields=[
                ('id', models.BigAutoField(
                    auto_created=True, primary_key=True,
                    serialize=False, verbose_name='ID'
                )),
                ('trigger', models.CharField(
                    choices=[
                        ('temps_long', 'Temps passé trop long sur un bloc'),
                        ('multi_reouverture', 'Bloc rouvert plusieurs fois'),
                        ('quiz_rate', 'Quiz raté ou score faible'),
                        ('sequence_complexe', 'Séquence trop complexe'),
                        ('module_difficile', 'Module difficile (score bas)'),
                        ('cours_abandonne', 'Cours abandonné (ratio < 30%)'),
                    ],
                    max_length=30, verbose_name='Trigger'
                )),
                ('status', models.CharField(
                    choices=[
                        ('pending', 'En attente'),
                        ('success', 'Succès'),
                        ('error', 'Erreur'),
                        ('skipped', 'Ignoré (doublon récent)'),
                    ],
                    default='pending', max_length=20, verbose_name='Statut'
                )),
                ('prompt_context', models.JSONField(blank=True, default=dict)),
                ('gpt_response', models.TextField(blank=True)),
                ('error_message', models.TextField(blank=True)),
                ('tokens_used', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('completed_at', models.DateTimeField(null=True, blank=True)),
                ('apprenant', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='ai_requests_analytics',
                    to=settings.AUTH_USER_MODEL,
                )),
                ('bloc', models.ForeignKey(
                    blank=True, null=True,
                    on_delete=django.db.models.deletion.SET_NULL,
                    related_name='ai_requests_analytics',
                    to='courses.bloccontenu',
                )),
                ('cours', models.ForeignKey(
                    blank=True, null=True,
                    on_delete=django.db.models.deletion.SET_NULL,
                    related_name='ai_requests_analytics',
                    to='courses.cours',
                )),
                ('module', models.ForeignKey(
                    blank=True, null=True,
                    on_delete=django.db.models.deletion.SET_NULL,
                    related_name='ai_requests_analytics',
                    to='courses.module',
                )),
                ('quiz', models.ForeignKey(
                    blank=True, null=True,
                    on_delete=django.db.models.deletion.SET_NULL,
                    related_name='ai_requests_analytics',
                    to='evaluations.quiz',
                )),
                ('sequence', models.ForeignKey(
                    blank=True, null=True,
                    on_delete=django.db.models.deletion.SET_NULL,
                    related_name='ai_requests_analytics',
                    to='courses.sequence',
                )),
            ],
            options={
                'verbose_name': 'Requête IA',
                'verbose_name_plural': 'Requêtes IA',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='AIAnalysisRequest',
            index=models.Index(
                fields=['apprenant', 'bloc', 'trigger'],
                name='analytics_ai_apprena_idx1'
            ),
        ),
        migrations.AddIndex(
            model_name='AIAnalysisRequest',
            index=models.Index(
                fields=['apprenant', 'quiz', 'trigger'],
                name='analytics_ai_apprena_idx2'
            ),
        ),

        # ── ContenuGenere ─────────────────────────────────────────────────
        migrations.CreateModel(
            name='ContenuGenere',
            fields=[
                ('id', models.BigAutoField(
                    auto_created=True, primary_key=True,
                    serialize=False, verbose_name='ID'
                )),
                ('type_contenu', models.CharField(
                    choices=[
                        ('bloc_simplifie', 'Bloc simplifié'),
                        ('bloc_alternatif', 'Approche alternative'),
                        ('sequence_adaptative', 'Séquence adaptative'),
                        ('module_revision', 'Module de révision'),
                        ('quiz_remediation', 'Quiz de remédiation'),
                    ],
                    max_length=30,
                )),
                ('titre', models.CharField(max_length=300)),
                ('description', models.TextField(blank=True)),
                ('contenu_html', models.TextField(blank=True)),
                ('contenu_json', models.JSONField(blank=True, default=dict)),
                ('concepts_cibles', models.JSONField(blank=True, default=list)),
                ('niveau_difficulte', models.CharField(
                    blank=True, max_length=20, null=True,
                    choices=[
                        ('debutant', 'Débutant'),
                        ('intermediaire', 'Intermédiaire'),
                        ('avance', 'Avancé'),
                    ],
                )),
                ('a_ete_consulte', models.BooleanField(default=False)),
                ('consulte_le', models.DateTimeField(blank=True, null=True)),
                ('a_aide', models.BooleanField(blank=True, null=True)),
                ('feedback_le', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ai_request', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='contenu_genere',
                    to='analytics.aianalysisrequest',
                )),
                ('apprenant', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='contenus_genere',
                    to=settings.AUTH_USER_MODEL,
                )),
                ('bloc_source', models.ForeignKey(
                    blank=True, null=True,
                    on_delete=django.db.models.deletion.SET_NULL,
                    related_name='contenus_generes',
                    to='courses.bloccontenu',
                )),
                ('module_source', models.ForeignKey(
                    blank=True, null=True,
                    on_delete=django.db.models.deletion.SET_NULL,
                    related_name='contenus_generes',
                    to='courses.module',
                )),
                ('quiz_source', models.ForeignKey(
                    blank=True, null=True,
                    on_delete=django.db.models.deletion.SET_NULL,
                    related_name='contenus_generes',
                    to='evaluations.quiz',
                )),
                ('sequence_source', models.ForeignKey(
                    blank=True, null=True,
                    on_delete=django.db.models.deletion.SET_NULL,
                    related_name='contenus_generes',
                    to='courses.sequence',
                )),
            ],
            options={
                'verbose_name': 'Contenu généré',
                'verbose_name_plural': 'Contenus générés',
                'ordering': ['-created_at'],
            },
        ),

        # ── QuizGenereClaude ────────────────────────────────────────────────
        migrations.CreateModel(
            name='QuizGenereClaude',
            fields=[
                ('id', models.BigAutoField(
                    auto_created=True, primary_key=True,
                    serialize=False, verbose_name='ID'
                )),
                ('titre', models.CharField(max_length=300)),
                ('consigne', models.TextField(blank=True)),
                ('questions', models.JSONField(default=list)),
                ('concepts_rates', models.JSONField(blank=True, default=list)),
                ('score_remediation', models.SmallIntegerField(blank=True, null=True)),
                ('passe_le', models.DateTimeField(blank=True, null=True)),
                ('remediation_reussie', models.BooleanField(blank=True, null=True)),
                ('a_ete_consulte', models.BooleanField(default=False)),
                ('consulte_le', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ai_request', models.OneToOneField(
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='quiz_genere',
                    to='analytics.aianalysisrequest',
                )),
                ('apprenant', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='quiz_generes_claude',
                    to=settings.AUTH_USER_MODEL,
                )),
                ('quiz_source', models.ForeignKey(
                    blank=True, null=True,
                    on_delete=django.db.models.deletion.SET_NULL,
                    related_name='quiz_generes_claude',
                    to='evaluations.quiz',
                )),
            ],
            options={
                'verbose_name': 'Quiz généré (Claude)',
                'verbose_name_plural': 'Quiz générés (Claude)',
                'ordering': ['-created_at'],
            },
        ),
    ]