# Generated by Django 5.1.6 on 2026-04-21 23:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0002_ai_models'),
        ('courses', '0016_alter_cours_departement'),
        ('evaluations', '0008_alter_question_fichier_enonce'),
        ('users', '0027_user_photo'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='aianalysisrequest',
            new_name='analytics_a_apprena_63d667_idx',
            old_name='analytics_ai_apprena_idx1',
        ),
        migrations.RenameIndex(
            model_name='aianalysisrequest',
            new_name='analytics_a_apprena_02349c_idx',
            old_name='analytics_ai_apprena_idx2',
        ),
        migrations.AlterField(
            model_name='aianalysisrequest',
            name='apprenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_requests', to='users.apprenant'),
        ),
        migrations.AlterField(
            model_name='aianalysisrequest',
            name='bloc',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='courses.bloccontenu'),
        ),
        migrations.AlterField(
            model_name='aianalysisrequest',
            name='cours',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='courses.cours'),
        ),
        migrations.AlterField(
            model_name='aianalysisrequest',
            name='module',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='courses.module'),
        ),
        migrations.AlterField(
            model_name='aianalysisrequest',
            name='quiz',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='evaluations.quiz'),
        ),
        migrations.AlterField(
            model_name='aianalysisrequest',
            name='sequence',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='courses.sequence'),
        ),
        migrations.AlterField(
            model_name='aianalysisrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'En attente'), ('success', 'Succès'), ('error', 'Erreur'), ('skipped', 'Ignoré (doublon récent)')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='aianalysisrequest',
            name='trigger',
            field=models.CharField(choices=[('temps_long', 'Temps passé trop long sur un bloc'), ('multi_reouverture', 'Bloc rouvert plusieurs fois'), ('quiz_rate', 'Quiz raté ou score faible'), ('sequence_complexe', 'Séquence trop complexe'), ('module_difficile', 'Module difficile (score bas)'), ('cours_abandonne', 'Cours abandonné (ratio < 30%)')], max_length=30),
        ),
        migrations.AlterField(
            model_name='contenugenere',
            name='apprenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contenus_genere', to='users.apprenant'),
        ),
        migrations.AlterField(
            model_name='contenugenere',
            name='contenu_html',
            field=models.TextField(blank=True, help_text='HTML pour affichage direct'),
        ),
        migrations.AlterField(
            model_name='contenugenere',
            name='contenu_json',
            field=models.JSONField(blank=True, default=dict, help_text='Données structurées'),
        ),
        migrations.AlterField(
            model_name='quizgenereclaude',
            name='apprenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_generes_claude', to='users.apprenant'),
        ),
    ]
