# Generated by Django 5.1.2 on 2024-11-17 17:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0002_initial'),
        ('evaluations', '0002_initial'),
        ('feedback', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='auteur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='users.user'),
        ),
        migrations.AddField(
            model_name='feedback',
            name='cours',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='courses.cours'),
        ),
        migrations.AddField(
            model_name='feedback',
            name='destinataires',
            field=models.ManyToManyField(blank=True, related_name='feedbacks_recus', to='users.user'),
        ),
        migrations.AddField(
            model_name='feedback',
            name='evaluation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='evaluations.evaluation'),
        ),
        migrations.AddField(
            model_name='progression',
            name='apprenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progressions', to='users.user'),
        ),
        migrations.AddField(
            model_name='progression',
            name='cours',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progressions', to='courses.cours'),
        ),
        migrations.AddField(
            model_name='planaction',
            name='progression',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plans_actions', to='feedback.progression'),
        ),
        migrations.AddField(
            model_name='historiqueprogression',
            name='progression',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historique', to='feedback.progression'),
        ),
    ]
