# Generated by Django 5.1.6 on 2025-12-28 16:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_initial'),
        ('users', '0023_remove_apprenant_classe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inscriptioncours',
            name='apprenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscriptions_cours', related_query_name='inscription_cours', to='users.apprenant'),
        ),
    ]
