# Generated by Django 5.1.6 on 2026-01-06 14:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0006_remove_classe_apprenants_inscription_classe_and_more'),
        ('courses', '0003_alter_inscriptioncours_apprenant'),
        ('users', '0023_remove_apprenant_classe'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='session',
            options={'ordering': ['-date_debut']},
        ),
        migrations.RenameField(
            model_name='cours',
            old_name='date',
            new_name='date_debut',
        ),
        migrations.RenameField(
            model_name='participation',
            old_name='date_participation',
            new_name='created_at',
        ),
        migrations.AlterUniqueTogether(
            name='participation',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='cours',
            name='heure',
        ),
        migrations.AddField(
            model_name='cours',
            name='date_fin',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cours',
            name='statut',
            field=models.CharField(choices=[('planifie', 'Planifié'), ('en_cours', 'En cours'), ('termine', 'Terminé'), ('annule', 'Annulé')], default='planifie', max_length=30),
        ),
        migrations.AddField(
            model_name='cours',
            name='volume_horaire',
            field=models.PositiveIntegerField(default=0, help_text='Volume horaire total prévu pour ce cours (en heures).'),
        ),
        migrations.AddField(
            model_name='participation',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='participation',
            name='source',
            field=models.CharField(choices=[('auto', 'Automatique'), ('manuel', 'Manuel')], default='manuel', help_text='auto ou manuel', max_length=10),
        ),
        migrations.AddField(
            model_name='participation',
            name='statut',
            field=models.CharField(choices=[('en_attente', 'En attente'), ('terminee', 'Terminée'), ('annulee', 'Annulée')], default='en_attente', max_length=15),
        ),
        migrations.AddField(
            model_name='session',
            name='participation_mode',
            field=models.CharField(choices=[('auto', 'Automatique'), ('manuel', 'Manuel')], default='manuel', help_text='auto = participation créée automatiquement à la fin; manuel = saisie volontaire', max_length=10),
        ),
        migrations.AlterField(
            model_name='cours',
            name='enseignant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cours_responsable', to='users.formateur'),
        ),
        migrations.AlterField(
            model_name='cours',
            name='groupe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cours', to='academics.groupe'),
        ),
        migrations.AlterField(
            model_name='cours',
            name='matiere',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cours', to='academics.matiere'),
        ),
        migrations.AlterField(
            model_name='inscriptioncours',
            name='statut',
            field=models.CharField(default='en_cours', help_text='Ex: suivi, en_cours, complete, annule', max_length=50),
        ),
        migrations.AlterField(
            model_name='module',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddConstraint(
            model_name='cours',
            constraint=models.UniqueConstraint(fields=('groupe', 'matiere', 'enseignant'), name='uniq_cours_groupe_matiere_enseignant'),
        ),
        migrations.AddConstraint(
            model_name='inscriptioncours',
            constraint=models.UniqueConstraint(fields=('apprenant', 'cours'), name='uniq_apprenant_par_cours'),
        ),
        migrations.AddConstraint(
            model_name='participation',
            constraint=models.UniqueConstraint(fields=('session', 'apprenant'), name='uniq_participation_session_apprenant'),
        ),
        migrations.AddConstraint(
            model_name='suivi',
            constraint=models.UniqueConstraint(fields=('apprenant', 'cours'), name='uniq_suivi_apprenant_cours'),
        ),
    ]
