# Generated by Django 5.1.6 on 2026-01-06 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_alter_session_options_rename_date_cours_date_debut_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cours',
            name='titre',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
