# Generated by Django 5.1.6 on 2026-01-15 18:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_cours_titre'),
    ]

    operations = [
        migrations.CreateModel(
            name='SequenceContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenu_texte', models.TextField(blank=True, default='')),
                ('contenu_html', models.TextField(blank=True, default='')),
                ('video_url', models.URLField(blank=True, null=True)),
                ('lien_externe', models.URLField(blank=True, null=True)),
                ('objectifs', models.TextField(blank=True, default='')),
                ('duree_estimee_minutes', models.PositiveIntegerField(default=0)),
                ('est_publie', models.BooleanField(default=False)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('sequence', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='contenu', to='courses.sequence')),
            ],
        ),
    ]
