# Generated by Django 5.1.6 on 2026-01-22 14:56

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_sequencecontent'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BlocContenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(help_text="Titre du bloc (ex: 'Introduction aux variables')", max_length=255)),
                ('type_bloc', models.CharField(choices=[('texte', 'Texte / Explication'), ('video', 'Vidéo'), ('audio', 'Audio'), ('image', 'Image'), ('code', 'Exemple de code'), ('exercice', 'Exercice pratique'), ('quiz', 'Quiz intégré'), ('lien', 'Lien externe'), ('pdf', 'Document PDF'), ('markdown', 'Contenu Markdown')], default='texte', max_length=20)),
                ('ordre', models.PositiveIntegerField(default=0, help_text="Ordre d'affichage dans la séquence")),
                ('contenu_texte', models.TextField(blank=True, default='', help_text='Contenu texte brut')),
                ('contenu_html', models.TextField(blank=True, default='', help_text='Contenu HTML enrichi')),
                ('contenu_markdown', models.TextField(blank=True, default='', help_text='Contenu en Markdown')),
                ('video_url', models.URLField(blank=True, help_text='URL YouTube, Vimeo, etc.', null=True)),
                ('audio_url', models.URLField(blank=True, help_text='URL fichier audio', null=True)),
                ('image', models.ImageField(blank=True, help_text='Image illustrative', null=True, upload_to='sequences/images/%Y/%m/')),
                ('fichier', models.FileField(blank=True, help_text='Fichier attaché (PDF, ZIP, etc.)', null=True, upload_to='sequences/fichiers/%Y/%m/')),
                ('lien_externe', models.URLField(blank=True, help_text='Lien vers une ressource externe', null=True)),
                ('code_source', models.TextField(blank=True, default='', help_text='Code source à afficher')),
                ('langage_code', models.CharField(blank=True, default='', help_text='Langage du code (python, javascript, etc.)', max_length=50)),
                ('objectifs', models.TextField(blank=True, default='', help_text='Objectifs pédagogiques de ce bloc')),
                ('duree_estimee_minutes', models.PositiveIntegerField(default=0, help_text='Durée estimée pour ce bloc', validators=[django.core.validators.MinValueValidator(0)])),
                ('est_obligatoire', models.BooleanField(default=True, help_text='Ce bloc doit-il être consulté obligatoirement ?')),
                ('est_visible', models.BooleanField(default=True, help_text='Le bloc est-il visible pour les apprenants ?')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('sequence', models.ForeignKey(help_text='Séquence parente', on_delete=django.db.models.deletion.CASCADE, related_name='blocs_contenu', to='courses.sequence')),
            ],
            options={
                'verbose_name': 'Bloc de contenu',
                'verbose_name_plural': 'Blocs de contenu',
                'ordering': ['sequence', 'ordre'],
                'indexes': [models.Index(fields=['sequence', 'ordre'], name='courses_blo_sequenc_2e5775_idx'), models.Index(fields=['type_bloc'], name='courses_blo_type_bl_4dd906_idx')],
                'unique_together': {('sequence', 'ordre')},
            },
        ),
        migrations.CreateModel(
            name='RessourceSequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(help_text='Nom de la ressource', max_length=255)),
                ('description', models.TextField(blank=True, default='', help_text='Description de la ressource')),
                ('fichier', models.FileField(help_text='Fichier de la ressource', upload_to='sequences/ressources/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx', 'ppt', 'pptx', 'xls', 'xlsx', 'zip', 'rar', 'jpg', 'jpeg', 'png', 'gif', 'txt', 'md', 'py', 'js', 'html', 'css'])])),
                ('type_ressource', models.CharField(choices=[('cours', 'Support de cours'), ('exercice', "Fichier d'exercice"), ('correction', 'Correction'), ('supplementaire', 'Ressource supplémentaire'), ('reference', 'Document de référence')], default='supplementaire', max_length=20)),
                ('taille_fichier', models.BigIntegerField(blank=True, help_text='Taille en octets (calculée automatiquement)', null=True)),
                ('est_telechargeable', models.BooleanField(default=True, help_text='Le fichier peut-il être téléchargé ?')),
                ('nombre_telechargements', models.IntegerField(default=0, help_text='Nombre de téléchargements')),
                ('ordre', models.PositiveIntegerField(default=0, help_text="Ordre d'affichage")),
                ('date_ajout', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('ajoute_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ressources_sequences_ajoutees', to=settings.AUTH_USER_MODEL)),
                ('sequence', models.ForeignKey(help_text='Séquence parente', on_delete=django.db.models.deletion.CASCADE, related_name='ressources_sequences', to='courses.sequence')),
            ],
            options={
                'verbose_name': 'Ressource de séquence',
                'verbose_name_plural': 'Ressources de séquences',
                'ordering': ['sequence', 'ordre'],
                'indexes': [models.Index(fields=['sequence', 'type_ressource'], name='courses_res_sequenc_afc652_idx')],
            },
        ),
    ]
