# Generated by Django 5.1.6 on 2026-01-29 14:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_bloccontenu_ressourcesequence'),
        ('users', '0023_remove_apprenant_classe'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoursProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('est_termine', models.BooleanField(default=False)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('apprenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cours_progress', to='users.apprenant')),
                ('cours', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses_progressions', related_query_name='courses_progression', to='courses.cours')),
            ],
        ),
        migrations.CreateModel(
            name='ModuleProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('est_termine', models.BooleanField(default=False)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('apprenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modules_progress', to='users.apprenant')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses_progressions', related_query_name='courses_progression', to='courses.module')),
            ],
        ),
        migrations.CreateModel(
            name='SequenceProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('est_termine', models.BooleanField(default=False)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('apprenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sequences_progress', to='users.apprenant')),
                ('sequence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses_progressions', related_query_name='courses_progression', to='courses.sequence')),
            ],
        ),
        migrations.CreateModel(
            name='BlocProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('est_termine', models.BooleanField(default=False)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('apprenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocs_progress', to='users.apprenant')),
                ('bloc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progressions', to='courses.bloccontenu')),
            ],
            options={
                'indexes': [models.Index(fields=['apprenant', 'bloc'], name='courses_blo_apprena_83f99d_idx'), models.Index(fields=['apprenant', 'est_termine'], name='courses_blo_apprena_e9ba5a_idx')],
                'constraints': [models.UniqueConstraint(fields=('apprenant', 'bloc'), name='uniq_progress_apprenant_bloc')],
            },
        ),
    ]
