# Generated by Django 5.1.6 on 2026-02-11 10:45

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0006_remove_classe_apprenants_inscription_classe_and_more'),
        ('courses', '0008_coursprogress_moduleprogress_sequenceprogress_and_more'),
        ('users', '0023_remove_apprenant_classe'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blocprogress',
            options={'verbose_name': 'Progression bloc', 'verbose_name_plural': 'Progressions blocs'},
        ),
        migrations.AlterModelOptions(
            name='cours',
            options={'ordering': ['-date_debut'], 'verbose_name': 'Cours', 'verbose_name_plural': 'Cours'},
        ),
        migrations.AlterModelOptions(
            name='coursprogress',
            options={'verbose_name': 'Progression cours', 'verbose_name_plural': 'Progressions cours'},
        ),
        migrations.AlterModelOptions(
            name='inscriptioncours',
            options={'verbose_name': 'Inscription cours', 'verbose_name_plural': 'Inscriptions cours'},
        ),
        migrations.AlterModelOptions(
            name='module',
            options={'ordering': ['id'], 'verbose_name': 'Module', 'verbose_name_plural': 'Modules'},
        ),
        migrations.AlterModelOptions(
            name='moduleprogress',
            options={'verbose_name': 'Progression module', 'verbose_name_plural': 'Progressions modules'},
        ),
        migrations.AlterModelOptions(
            name='participation',
            options={'verbose_name': 'Participation', 'verbose_name_plural': 'Participations'},
        ),
        migrations.AlterModelOptions(
            name='ressourcesequence',
            options={'ordering': ['sequence', 'ordre'], 'verbose_name': 'Ressource de sÃ©quence', 'verbose_name_plural': 'Ressources de sÃ©quences'},
        ),
        migrations.AlterModelOptions(
            name='sequence',
            options={'ordering': ['id'], 'verbose_name': 'SÃ©quence', 'verbose_name_plural': 'SÃ©quences'},
        ),
        migrations.AlterModelOptions(
            name='sequencecontent',
            options={'verbose_name': 'Contenu de sÃ©quence', 'verbose_name_plural': 'Contenus de sÃ©quences'},
        ),
        migrations.AlterModelOptions(
            name='sequenceprogress',
            options={'verbose_name': 'Progression sÃ©quence', 'verbose_name_plural': 'Progressions sÃ©quences'},
        ),
        migrations.AlterModelOptions(
            name='session',
            options={'ordering': ['-date_debut'], 'verbose_name': 'Session', 'verbose_name_plural': 'Sessions'},
        ),
        migrations.AlterModelOptions(
            name='suivi',
            options={'verbose_name': 'Suivi', 'verbose_name_plural': 'Suivis'},
        ),
        migrations.RemoveConstraint(
            model_name='blocprogress',
            name='uniq_progress_apprenant_bloc',
        ),
        migrations.RemoveConstraint(
            model_name='cours',
            name='uniq_cours_groupe_matiere_enseignant',
        ),
        migrations.RemoveConstraint(
            model_name='inscriptioncours',
            name='uniq_apprenant_par_cours',
        ),
        migrations.RemoveConstraint(
            model_name='participation',
            name='uniq_participation_session_apprenant',
        ),
        migrations.RemoveConstraint(
            model_name='suivi',
            name='uniq_suivi_apprenant_cours',
        ),
        migrations.RemoveIndex(
            model_name='bloccontenu',
            name='courses_blo_sequenc_2e5775_idx',
        ),
        migrations.RemoveIndex(
            model_name='bloccontenu',
            name='courses_blo_type_bl_4dd906_idx',
        ),
        migrations.RemoveIndex(
            model_name='blocprogress',
            name='courses_blo_apprena_83f99d_idx',
        ),
        migrations.RemoveIndex(
            model_name='blocprogress',
            name='courses_blo_apprena_e9ba5a_idx',
        ),
        migrations.RemoveIndex(
            model_name='ressourcesequence',
            name='courses_res_sequenc_afc652_idx',
        ),
        migrations.AlterUniqueTogether(
            name='bloccontenu',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='cours',
            name='annee_scolaire',
            field=models.ForeignKey(blank=True, help_text='AnnÃ©e scolaire Ã  laquelle ce cours est rattachÃ©', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cours', to='academics.anneescolaire'),
        ),
        migrations.AddField(
            model_name='cours',
            name='institution',
            field=models.ForeignKey(blank=True, help_text='Ã‰tablissement auquel ce cours est rattachÃ©', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cours', to='academics.institution'),
        ),
        migrations.AddField(
            model_name='inscriptioncours',
            name='annee_scolaire',
            field=models.ForeignKey(blank=True, help_text='HÃ©ritÃ© du cours', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inscriptions_cours', to='academics.anneescolaire'),
        ),
        migrations.AddField(
            model_name='inscriptioncours',
            name='institution',
            field=models.ForeignKey(blank=True, help_text='HÃ©ritÃ© du cours', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inscriptions_cours', to='academics.institution'),
        ),
        migrations.AddField(
            model_name='module',
            name='annee_scolaire',
            field=models.ForeignKey(blank=True, help_text='HÃ©ritÃ© du cours parent', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='modules', to='academics.anneescolaire'),
        ),
        migrations.AddField(
            model_name='module',
            name='institution',
            field=models.ForeignKey(blank=True, help_text='HÃ©ritÃ© du cours parent', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='modules', to='academics.institution'),
        ),
        migrations.AddField(
            model_name='participation',
            name='annee_scolaire',
            field=models.ForeignKey(blank=True, help_text='HÃ©ritÃ© de la session', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='participations', to='academics.anneescolaire'),
        ),
        migrations.AddField(
            model_name='participation',
            name='institution',
            field=models.ForeignKey(blank=True, help_text='HÃ©ritÃ© de la session', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='participations', to='academics.institution'),
        ),
        migrations.AddField(
            model_name='sequence',
            name='annee_scolaire',
            field=models.ForeignKey(blank=True, help_text='HÃ©ritÃ© du module parent', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sequences', to='academics.anneescolaire'),
        ),
        migrations.AddField(
            model_name='sequence',
            name='institution',
            field=models.ForeignKey(blank=True, help_text='HÃ©ritÃ© du module parent', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sequences', to='academics.institution'),
        ),
        migrations.AddField(
            model_name='session',
            name='annee_scolaire',
            field=models.ForeignKey(blank=True, help_text='HÃ©ritÃ© du cours', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='academics.anneescolaire'),
        ),
        migrations.AddField(
            model_name='session',
            name='institution',
            field=models.ForeignKey(blank=True, help_text='HÃ©ritÃ© du cours', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='academics.institution'),
        ),
        migrations.AddField(
            model_name='suivi',
            name='annee_scolaire',
            field=models.ForeignKey(blank=True, help_text='HÃ©ritÃ© du cours', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='suivis', to='academics.anneescolaire'),
        ),
        migrations.AddField(
            model_name='suivi',
            name='institution',
            field=models.ForeignKey(blank=True, help_text='HÃ©ritÃ© du cours', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='suivis', to='academics.institution'),
        ),
        migrations.AlterField(
            model_name='bloccontenu',
            name='audio_url',
            field=models.URLField(blank=True, null=True, verbose_name="URL de l'audio"),
        ),
        migrations.AlterField(
            model_name='bloccontenu',
            name='code_source',
            field=models.TextField(blank=True, null=True, verbose_name='Code source'),
        ),
        migrations.AlterField(
            model_name='bloccontenu',
            name='contenu_html',
            field=models.TextField(blank=True, null=True, verbose_name='Contenu HTML'),
        ),
        migrations.AlterField(
            model_name='bloccontenu',
            name='contenu_markdown',
            field=models.TextField(blank=True, null=True, verbose_name='Contenu Markdown'),
        ),
        migrations.AlterField(
            model_name='bloccontenu',
            name='contenu_texte',
            field=models.TextField(blank=True, null=True, verbose_name='Contenu texte'),
        ),
        migrations.AlterField(
            model_name='bloccontenu',
            name='duree_estimee_minutes',
            field=models.PositiveIntegerField(default=0, verbose_name='DurÃ©e estimÃ©e (minutes)'),
        ),
        migrations.AlterField(
            model_name='bloccontenu',
            name='est_obligatoire',
            field=models.BooleanField(default=True, verbose_name='Contenu obligatoire'),
        ),
        migrations.AlterField(
            model_name='bloccontenu',
            name='est_visible',
            field=models.BooleanField(default=True, verbose_name='Visible pour les apprenants'),
        ),
        migrations.AlterField(
            model_name='bloccontenu',
            name='fichier',
            field=models.FileField(blank=True, null=True, upload_to='blocs_contenu/fichiers/', verbose_name='Fichier'),
        ),
        migrations.AlterField(
            model_name='bloccontenu',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='blocs_contenu/images/', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='bloccontenu',
            name='langage_code',
            field=models.CharField(blank=True, choices=[('python', 'Python'), ('javascript', 'JavaScript'), ('java', 'Java'), ('c', 'C'), ('cpp', 'C++'), ('csharp', 'C#'), ('php', 'PHP'), ('ruby', 'Ruby'), ('go', 'Go'), ('rust', 'Rust'), ('sql', 'SQL'), ('html', 'HTML'), ('css', 'CSS'), ('other', 'Autre')], max_length=20, null=True, verbose_name='Langage de programmation'),
        ),
        migrations.AlterField(
            model_name='bloccontenu',
            name='lien_externe',
            field=models.URLField(blank=True, null=True, verbose_name='Lien externe'),
        ),
        migrations.AlterField(
            model_name='bloccontenu',
            name='objectifs',
            field=models.TextField(blank=True, null=True, verbose_name='Objectifs pÃ©dagogiques'),
        ),
        migrations.AlterField(
            model_name='bloccontenu',
            name='ordre',
            field=models.PositiveIntegerField(default=0, verbose_name="Ordre d'affichage"),
        ),
        migrations.AlterField(
            model_name='bloccontenu',
            name='sequence',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocs_contenu', to='courses.sequence', verbose_name='SÃ©quence'),
        ),
        migrations.AlterField(
            model_name='bloccontenu',
            name='titre',
            field=models.CharField(max_length=255, verbose_name='Titre du bloc'),
        ),
        migrations.AlterField(
            model_name='bloccontenu',
            name='type_bloc',
            field=models.CharField(choices=[('texte', 'Texte'), ('html', 'HTML'), ('markdown', 'Markdown'), ('video', 'VidÃ©o'), ('audio', 'Audio'), ('image', 'Image'), ('fichier', 'Fichier'), ('lien', 'Lien externe'), ('code', 'Code source')], max_length=20, verbose_name='Type de bloc'),
        ),
        migrations.AlterField(
            model_name='bloccontenu',
            name='video_url',
            field=models.URLField(blank=True, null=True, verbose_name='URL de la vidÃ©o'),
        ),
        migrations.AlterField(
            model_name='blocprogress',
            name='bloc',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_records', to='courses.bloccontenu'),
        ),
        migrations.AlterField(
            model_name='cours',
            name='enseignant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cours_enseignes', to='users.formateur'),
        ),
        migrations.AlterField(
            model_name='cours',
            name='statut',
            field=models.CharField(choices=[('en_cours', 'En cours'), ('termine', 'TerminÃ©'), ('planifie', 'PlanifiÃ©')], default='planifie', max_length=20),
        ),
        migrations.AlterField(
            model_name='cours',
            name='titre',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='cours',
            name='volume_horaire',
            field=models.IntegerField(default=0, help_text='Volume horaire prÃ©vu en minutes'),
        ),
        migrations.AlterField(
            model_name='coursprogress',
            name='cours',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_records', to='courses.cours'),
        ),
        migrations.AlterField(
            model_name='inscriptioncours',
            name='apprenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscriptions_cours', to='users.apprenant'),
        ),
        migrations.AlterField(
            model_name='inscriptioncours',
            name='date_inscription',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='inscriptioncours',
            name='statut',
            field=models.CharField(choices=[('inscrit', 'Inscrit'), ('en_cours', 'En cours'), ('termine', 'TerminÃ©'), ('abandonne', 'AbandonnÃ©')], default='inscrit', max_length=20),
        ),
        migrations.AlterField(
            model_name='module',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='moduleprogress',
            name='module',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_records', to='courses.module'),
        ),
        migrations.AlterField(
            model_name='participation',
            name='source',
            field=models.CharField(choices=[('manuelle', 'Manuelle'), ('auto', 'Automatique'), ('importee', 'ImportÃ©e')], default='manuelle', max_length=20),
        ),
        migrations.AlterField(
            model_name='participation',
            name='statut',
            field=models.CharField(choices=[('present', 'PrÃ©sent'), ('absent', 'Absent'), ('retard', 'Retard'), ('excuse', 'ExcusÃ©')], default='present', max_length=20),
        ),
        migrations.AlterField(
            model_name='ressourcesequence',
            name='ajoute_par',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ressources_ajoutees', to='users.formateur', verbose_name='AjoutÃ© par'),
        ),
        migrations.AlterField(
            model_name='ressourcesequence',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='ressourcesequence',
            name='est_telechargeable',
            field=models.BooleanField(default=True, verbose_name='Autoriser le tÃ©lÃ©chargement'),
        ),
        migrations.AlterField(
            model_name='ressourcesequence',
            name='fichier',
            field=models.FileField(upload_to='ressources_sequences/', verbose_name='Fichier'),
        ),
        migrations.AlterField(
            model_name='ressourcesequence',
            name='nombre_telechargements',
            field=models.PositiveIntegerField(default=0, verbose_name='Nombre de tÃ©lÃ©chargements'),
        ),
        migrations.AlterField(
            model_name='ressourcesequence',
            name='ordre',
            field=models.PositiveIntegerField(default=0, verbose_name="Ordre d'affichage"),
        ),
        migrations.AlterField(
            model_name='ressourcesequence',
            name='sequence',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ressources_sequences', to='courses.sequence', verbose_name='SÃ©quence'),
        ),
        migrations.AlterField(
            model_name='ressourcesequence',
            name='taille_fichier',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='Taille du fichier (octets)'),
        ),
        migrations.AlterField(
            model_name='ressourcesequence',
            name='titre',
            field=models.CharField(max_length=255, verbose_name='Titre de la ressource'),
        ),
        migrations.AlterField(
            model_name='ressourcesequence',
            name='type_ressource',
            field=models.CharField(choices=[('document', 'Document'), ('presentation', 'PrÃ©sentation'), ('tableur', 'Tableur'), ('pdf', 'PDF'), ('archive', 'Archive'), ('autre', 'Autre')], default='autre', max_length=20, verbose_name='Type de ressource'),
        ),
        migrations.AlterField(
            model_name='sequencecontent',
            name='contenu_html',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sequencecontent',
            name='contenu_texte',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sequencecontent',
            name='duree_estimee_minutes',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='sequencecontent',
            name='objectifs',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sequenceprogress',
            name='sequence',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_records', to='courses.sequence'),
        ),
        migrations.AlterField(
            model_name='session',
            name='formateur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions_animees', to='users.formateur'),
        ),
        migrations.AlterField(
            model_name='session',
            name='participation_mode',
            field=models.CharField(choices=[('presentiel', 'PrÃ©sentiel'), ('distanciel', 'Distanciel'), ('hybride', 'Hybride')], default='presentiel', max_length=20),
        ),
        migrations.AlterField(
            model_name='suivi',
            name='date_debut',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='suivi',
            name='note',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='suivi',
            name='progression',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterUniqueTogether(
            name='blocprogress',
            unique_together={('apprenant', 'bloc')},
        ),
        migrations.AlterUniqueTogether(
            name='coursprogress',
            unique_together={('apprenant', 'cours')},
        ),
        migrations.AlterUniqueTogether(
            name='inscriptioncours',
            unique_together={('apprenant', 'cours')},
        ),
        migrations.AlterUniqueTogether(
            name='moduleprogress',
            unique_together={('apprenant', 'module')},
        ),
        migrations.AlterUniqueTogether(
            name='participation',
            unique_together={('session', 'apprenant')},
        ),
        migrations.AlterUniqueTogether(
            name='sequenceprogress',
            unique_together={('apprenant', 'sequence')},
        ),
        migrations.AlterUniqueTogether(
            name='suivi',
            unique_together={('apprenant', 'cours')},
        ),
        migrations.AddConstraint(
            model_name='cours',
            constraint=models.UniqueConstraint(fields=('groupe', 'matiere', 'enseignant', 'annee_scolaire'), name='unique_cours_per_year'),
        ),
    ]
