# Generated by Django 5.1.6 on 2026-02-11 15:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0009_alter_blocprogress_options_alter_cours_options_and_more'),
        ('users', '0025_alter_admin_options_alter_apprenant_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bloccontenu',
            name='createur',
            field=models.ForeignKey(blank=True, help_text='Formateur qui a créé ce bloc de contenu', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blocs_contenu_crees', to='users.formateur'),
        ),
        migrations.AddField(
            model_name='module',
            name='createur',
            field=models.ForeignKey(blank=True, help_text='Formateur qui a créé ce module', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modules_crees', to='users.formateur'),
        ),
        migrations.AddField(
            model_name='sequence',
            name='createur',
            field=models.ForeignKey(blank=True, help_text='Formateur qui a créé cette séquence', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sequences_creees', to='users.formateur'),
        ),
    ]
