# Generated by Django 5.1.6 on 2026-02-11 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0010_bloccontenu_createur_module_createur_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bloccontenu',
            name='createur',
        ),
        migrations.RemoveField(
            model_name='module',
            name='createur',
        ),
        migrations.RemoveField(
            model_name='sequence',
            name='createur',
        ),
    ]
