# Generated by Django 5.1.6 on 2026-02-12 00:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0008_alter_domaineetude_options_alter_filiere_options_and_more'),
        ('courses', '0011_remove_bloccontenu_createur_remove_module_createur_and_more'),
        ('users', '0026_alter_admin_options_alter_apprenant_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ressourcesequence',
            options={'ordering': ['sequence', 'ordre'], 'verbose_name': 'Ressource de séquence', 'verbose_name_plural': 'Ressources de séquences'},
        ),
        migrations.AlterModelOptions(
            name='sequence',
            options={'ordering': ['id'], 'verbose_name': 'Séquence', 'verbose_name_plural': 'Séquences'},
        ),
        migrations.AlterModelOptions(
            name='sequencecontent',
            options={'verbose_name': 'Contenu de séquence', 'verbose_name_plural': 'Contenus de séquences'},
        ),
        migrations.AlterModelOptions(
            name='sequenceprogress',
            options={'verbose_name': 'Progression séquence', 'verbose_name_plural': 'Progressions séquences'},
        ),
        migrations.AlterField(
            model_name='bloccontenu',
            name='duree_estimee_minutes',
            field=models.PositiveIntegerField(default=0, verbose_name='Durée estimée (minutes)'),
        ),
        migrations.AlterField(
            model_name='bloccontenu',
            name='objectifs',
            field=models.TextField(blank=True, null=True, verbose_name='Objectifs pédagogiques'),
        ),
        migrations.AlterField(
            model_name='bloccontenu',
            name='sequence',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocs_contenu', to='courses.sequence', verbose_name='Séquence'),
        ),
        migrations.AlterField(
            model_name='bloccontenu',
            name='type_bloc',
            field=models.CharField(choices=[('texte', 'Texte'), ('html', 'HTML'), ('markdown', 'Markdown'), ('video', 'Vidéo'), ('audio', 'Audio'), ('image', 'Image'), ('fichier', 'Fichier'), ('lien', 'Lien externe'), ('code', 'Code source')], max_length=20, verbose_name='Type de bloc'),
        ),
        migrations.AlterField(
            model_name='bloccontenu',
            name='video_url',
            field=models.URLField(blank=True, null=True, verbose_name='URL de la vidéo'),
        ),
        migrations.AlterField(
            model_name='cours',
            name='annee_scolaire',
            field=models.ForeignKey(blank=True, help_text='Année scolaire à laquelle ce cours est rattaché', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cours', to='academics.anneescolaire'),
        ),
        migrations.AlterField(
            model_name='cours',
            name='institution',
            field=models.ForeignKey(blank=True, help_text='Établissement auquel ce cours est rattaché', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cours', to='academics.institution'),
        ),
        migrations.AlterField(
            model_name='cours',
            name='statut',
            field=models.CharField(choices=[('en_cours', 'En cours'), ('termine', 'Terminé'), ('planifie', 'Planifié')], default='planifie', max_length=20),
        ),
        migrations.AlterField(
            model_name='cours',
            name='volume_horaire',
            field=models.IntegerField(default=0, help_text='Volume horaire prévu en minutes'),
        ),
        migrations.AlterField(
            model_name='inscriptioncours',
            name='annee_scolaire',
            field=models.ForeignKey(blank=True, help_text='Hérité du cours', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inscriptions_cours', to='academics.anneescolaire'),
        ),
        migrations.AlterField(
            model_name='inscriptioncours',
            name='institution',
            field=models.ForeignKey(blank=True, help_text='Hérité du cours', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inscriptions_cours', to='academics.institution'),
        ),
        migrations.AlterField(
            model_name='inscriptioncours',
            name='statut',
            field=models.CharField(choices=[('inscrit', 'Inscrit'), ('en_cours', 'En cours'), ('termine', 'Terminé'), ('abandonne', 'Abandonné')], default='inscrit', max_length=20),
        ),
        migrations.AlterField(
            model_name='module',
            name='annee_scolaire',
            field=models.ForeignKey(blank=True, help_text='Hérité du cours parent', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='modules', to='academics.anneescolaire'),
        ),
        migrations.AlterField(
            model_name='module',
            name='institution',
            field=models.ForeignKey(blank=True, help_text='Hérité du cours parent', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='modules', to='academics.institution'),
        ),
        migrations.AlterField(
            model_name='participation',
            name='annee_scolaire',
            field=models.ForeignKey(blank=True, help_text='Hérité de la session', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='participations', to='academics.anneescolaire'),
        ),
        migrations.AlterField(
            model_name='participation',
            name='institution',
            field=models.ForeignKey(blank=True, help_text='Hérité de la session', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='participations', to='academics.institution'),
        ),
        migrations.AlterField(
            model_name='participation',
            name='source',
            field=models.CharField(choices=[('manuelle', 'Manuelle'), ('auto', 'Automatique'), ('importee', 'Importée')], default='manuelle', max_length=20),
        ),
        migrations.AlterField(
            model_name='participation',
            name='statut',
            field=models.CharField(choices=[('present', 'Présent'), ('absent', 'Absent'), ('retard', 'Retard'), ('excuse', 'Excusé')], default='present', max_length=20),
        ),
        migrations.AlterField(
            model_name='ressourcesequence',
            name='ajoute_par',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ressources_ajoutees', to='users.formateur', verbose_name='Ajouté par'),
        ),
        migrations.AlterField(
            model_name='ressourcesequence',
            name='est_telechargeable',
            field=models.BooleanField(default=True, verbose_name='Autoriser le téléchargement'),
        ),
        migrations.AlterField(
            model_name='ressourcesequence',
            name='nombre_telechargements',
            field=models.PositiveIntegerField(default=0, verbose_name='Nombre de téléchargements'),
        ),
        migrations.AlterField(
            model_name='ressourcesequence',
            name='sequence',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ressources_sequences', to='courses.sequence', verbose_name='Séquence'),
        ),
        migrations.AlterField(
            model_name='ressourcesequence',
            name='type_ressource',
            field=models.CharField(choices=[('document', 'Document'), ('presentation', 'Présentation'), ('tableur', 'Tableur'), ('pdf', 'PDF'), ('archive', 'Archive'), ('autre', 'Autre')], default='autre', max_length=20, verbose_name='Type de ressource'),
        ),
        migrations.AlterField(
            model_name='sequence',
            name='annee_scolaire',
            field=models.ForeignKey(blank=True, help_text='Hérité du module parent', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sequences', to='academics.anneescolaire'),
        ),
        migrations.AlterField(
            model_name='sequence',
            name='institution',
            field=models.ForeignKey(blank=True, help_text='Hérité du module parent', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sequences', to='academics.institution'),
        ),
        migrations.AlterField(
            model_name='session',
            name='annee_scolaire',
            field=models.ForeignKey(blank=True, help_text='Hérité du cours', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='academics.anneescolaire'),
        ),
        migrations.AlterField(
            model_name='session',
            name='institution',
            field=models.ForeignKey(blank=True, help_text='Hérité du cours', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='academics.institution'),
        ),
        migrations.AlterField(
            model_name='session',
            name='participation_mode',
            field=models.CharField(choices=[('presentiel', 'Présentiel'), ('distanciel', 'Distanciel'), ('hybride', 'Hybride')], default='presentiel', max_length=20),
        ),
        migrations.AlterField(
            model_name='suivi',
            name='annee_scolaire',
            field=models.ForeignKey(blank=True, help_text='Hérité du cours', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='suivis', to='academics.anneescolaire'),
        ),
        migrations.AlterField(
            model_name='suivi',
            name='institution',
            field=models.ForeignKey(blank=True, help_text='Hérité du cours', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='suivis', to='academics.institution'),
        ),
    ]
