# Generated by Django 5.1.6 on 2026-02-20 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0012_alter_ressourcesequence_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participation',
            name='source',
            field=models.CharField(choices=[('manuelle', 'Manuelle'), ('auto', 'Automatique')], default='manuelle', max_length=20),
        ),
    ]
