# Generated by Django 5.1.6 on 2026-02-20 10:26

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0013_alter_participation_source'),
        ('evaluations', '0007_merge_20260212_1727'),
        ('users', '0026_alter_admin_options_alter_apprenant_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIAnalysisRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trigger', models.CharField(choices=[('temps_long', 'Temps passé trop long sur un bloc'), ('quiz_rate', 'Quiz raté ou score faible'), ('scroll_faible', 'Scroll insuffisant (bloc peu lu)'), ('multi_reouverture', 'Bloc réouvert plusieurs fois')], max_length=30)),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('success', 'Succès'), ('error', 'Erreur'), ('skipped', 'Ignoré (doublon récent)')], default='pending', max_length=20)),
                ('prompt_context', models.JSONField(blank=True, default=dict)),
                ('gpt_response', models.TextField(blank=True)),
                ('error_message', models.TextField(blank=True)),
                ('tokens_used', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('apprenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_requests', to='users.apprenant')),
                ('bloc', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='courses.bloccontenu')),
                ('cours', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='courses.cours')),
                ('quiz', models.ForeignKey(blank=True, help_text='Renseigné uniquement pour le trigger quiz_rate', null=True, on_delete=django.db.models.deletion.SET_NULL, to='evaluations.quiz')),
                ('sequence', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='courses.sequence')),
            ],
            options={
                'verbose_name': 'Requête IA',
                'verbose_name_plural': 'Requêtes IA',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BlocGenere',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_generation', models.CharField(choices=[('explication_simple', 'Explication simplifiée'), ('analogie', 'Analogie / métaphore'), ('exemples', 'Exemples concrets'), ('resume', 'Résumé en points clés'), ('faq', 'FAQ — questions fréquentes')], default='explication_simple', max_length=30)),
                ('titre', models.CharField(max_length=300)),
                ('contenu_html', models.TextField()),
                ('concepts_cibles', models.JSONField(blank=True, default=list)),
                ('a_aide', models.BooleanField(blank=True, null=True)),
                ('feedback_le', models.DateTimeField(blank=True, null=True)),
                ('a_ete_consulte', models.BooleanField(default=False)),
                ('consulte_le', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('ai_request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bloc_genere', to='courses.aianalysisrequest')),
                ('apprenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocs_generes', to='users.apprenant')),
                ('bloc_source', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blocs_generes', to='courses.bloccontenu')),
            ],
            options={
                'verbose_name': 'Bloc généré',
                'verbose_name_plural': 'Blocs générés',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='QuizGenere',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=300)),
                ('consigne', models.TextField(blank=True)),
                ('questions', models.JSONField(default=list)),
                ('concepts_rates', models.JSONField(blank=True, default=list)),
                ('score_remediation', models.SmallIntegerField(blank=True, null=True)),
                ('passe_le', models.DateTimeField(blank=True, null=True)),
                ('remediation_reussie', models.BooleanField(blank=True, null=True)),
                ('a_ete_consulte', models.BooleanField(default=False)),
                ('consulte_le', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('ai_request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_genere', to='courses.aianalysisrequest')),
                ('apprenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_generes', to='users.apprenant')),
                ('quiz_source', models.ForeignKey(help_text='Quiz original dont les questions ont été ratées', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quiz_generes', to='evaluations.quiz')),
            ],
            options={
                'verbose_name': 'Quiz généré',
                'verbose_name_plural': 'Quiz générés',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='aianalysisrequest',
            index=models.Index(fields=['apprenant', 'bloc', 'trigger'], name='courses_aia_apprena_fd14b5_idx'),
        ),
        migrations.AddIndex(
            model_name='aianalysisrequest',
            index=models.Index(fields=['apprenant', 'quiz', 'trigger'], name='courses_aia_apprena_9c9735_idx'),
        ),
    ]
