# Generated by Django 5.1.6 on 2026-03-19 13:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0014_domaineetude_departement'),
        ('courses', '0014_aianalysisrequest_blocgenere_quizgenere_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cours',
            name='departement',
            field=models.ForeignKey(blank=True, help_text='Département auquel ce cours est rattaché', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cours', to='academics.departement'),
        ),
    ]
