# Generated by Django 5.1.6 on 2026-03-20 12:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0014_domaineetude_departement'),
        ('courses', '0015_cours_departement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cours',
            name='departement',
            field=models.ForeignKey(blank=True, help_text='Département hérité du groupe/classe', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cours', to='academics.departement'),
        ),
    ]
