# Generated by Django 5.2.12 on 2026-04-21 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0016_alter_cours_departement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloccontenu',
            name='fichier',
            field=models.FileField(blank=True, null=True, upload_to='uploads/blocs/fichiers/', verbose_name='Fichier'),
        ),
        migrations.AlterField(
            model_name='bloccontenu',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/blocs/images/', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='ressourcesequence',
            name='fichier',
            field=models.FileField(upload_to='uploads/ressources_sequences/', verbose_name='Fichier'),
        ),
    ]
