# Generated by Django 5.1.6 on 2026-04-21 23:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0018_alter_bloccontenu_fichier_alter_bloccontenu_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blocgenere',
            name='ai_request',
        ),
        migrations.RemoveField(
            model_name='quizgenere',
            name='ai_request',
        ),
        migrations.RemoveField(
            model_name='blocgenere',
            name='apprenant',
        ),
        migrations.RemoveField(
            model_name='blocgenere',
            name='bloc_source',
        ),
        migrations.RemoveField(
            model_name='quizgenere',
            name='apprenant',
        ),
        migrations.RemoveField(
            model_name='quizgenere',
            name='quiz_source',
        ),
        migrations.DeleteModel(
            name='AIAnalysisRequest',
        ),
        migrations.DeleteModel(
            name='BlocGenere',
        ),
        migrations.DeleteModel(
            name='QuizGenere',
        ),
    ]
