# Generated by Django 5.1.2 on 2024-11-17 17:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0001_initial'),
        ('locations', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='classe',
            name='apprenants',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='apprenants_classe_institution', to='users.apprenant'),
        ),
        migrations.AddField(
            model_name='departement',
            name='responsable_academique',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departements', to='users.responsableacademique'),
        ),
        migrations.AddField(
            model_name='filiere',
            name='domaine_etude',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='filieres', to='academics.domaineetude'),
        ),
        migrations.AddField(
            model_name='classe',
            name='filieres',
            field=models.ManyToManyField(related_name='classes', to='academics.filiere'),
        ),
        migrations.AddField(
            model_name='groupe',
            name='enseignants',
            field=models.ManyToManyField(related_name='academics_groupes', to='users.formateur'),
        ),
        migrations.AddField(
            model_name='classe',
            name='groupes',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='classe', to='academics.groupe'),
        ),
        migrations.AddField(
            model_name='inscription',
            name='annee_scolaire',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics.anneescolaire'),
        ),
        migrations.AddField(
            model_name='inscription',
            name='apprenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.apprenant'),
        ),
        migrations.AddField(
            model_name='institution',
            name='formateurs',
            field=models.ManyToManyField(related_name='institutions_academics', to='users.formateur'),
        ),
        migrations.AddField(
            model_name='institution',
            name='pays',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='etablissements', to='locations.pays'),
        ),
        migrations.AddField(
            model_name='inscription',
            name='institution',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics.institution'),
        ),
        migrations.AddField(
            model_name='departement',
            name='institution',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departements', to='academics.institution'),
        ),
        migrations.AddField(
            model_name='classe',
            name='matieres',
            field=models.ManyToManyField(related_name='classes', to='academics.matiere'),
        ),
    ]
