# Generated by Django 5.1.2 on 2024-11-18 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='anneescolaire',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='classe',
            name='date_creation',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='classe',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='departement',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='domaineetude',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='filiere',
            name='date_creation',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='filiere',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='filiere',
            name='statut',
            field=models.CharField(choices=[('actif', 'Actif'), ('en_pause', 'En Pause'), ('archive', 'Archivée')], default='actif', max_length=50),
        ),
        migrations.AddField(
            model_name='groupe',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inscription',
            name='statut_paiement',
            field=models.CharField(choices=[('en_attente', 'En attente'), ('payé', 'Payé'), ('annulé', 'Annulé')], default='en_attente', max_length=20),
        ),
        migrations.AddField(
            model_name='institution',
            name='accreditations',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='institution',
            name='adresse',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='institution',
            name='date_creation',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='institution',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='institution',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='institution',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='institution_logos/'),
        ),
        migrations.AddField(
            model_name='institution',
            name='nombre_etudiants',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='institution',
            name='site_web',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='institution',
            name='statut',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=50),
        ),
        migrations.AddField(
            model_name='institution',
            name='telephone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='institution',
            name='type_institution',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='matiere',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
