# Generated by Django 5.1.6 on 2025-04-24 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0003_anneescolaire_description_classe_date_creation_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='institution',
            old_name='telephone',
            new_name='telephone_1',
        ),
        migrations.AddField(
            model_name='institution',
            name='telephone_2',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
