# Generated by Django 5.1.6 on 2025-12-28 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0004_rename_telephone_institution_telephone_1_and_more'),
        ('users', '0021_alter_admin_date_entree_alter_admin_institution_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='institution',
            name='formateurs',
        ),
        migrations.RemoveField(
            model_name='classe',
            name='apprenants',
        ),
        migrations.AddField(
            model_name='classe',
            name='apprenants',
            field=models.ManyToManyField(blank=True, related_name='classes', to='users.apprenant'),
        ),
    ]
