# Generated by Django 5.1.6 on 2025-09-29 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0004_rename_telephone_institution_telephone_1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='classe',
            name='groupes',
            field=models.ManyToManyField(blank=True, null=True, related_name='classe', to='academics.groupe'),
        ),
    ]
