# Generated by Django 5.1.6 on 2025-12-28 16:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0005_remove_institution_formateurs_and_more'),
        ('users', '0023_remove_apprenant_classe'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classe',
            name='apprenants',
        ),
        migrations.AddField(
            model_name='inscription',
            name='classe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inscriptions', to='academics.classe'),
        ),
        migrations.AlterField(
            model_name='inscription',
            name='annee_scolaire',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscriptions', to='academics.anneescolaire'),
        ),
        migrations.AlterField(
            model_name='inscription',
            name='apprenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscriptions_scolaires', related_query_name='inscription_scolaire', to='users.apprenant'),
        ),
        migrations.AlterField(
            model_name='inscription',
            name='institution',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscriptions', to='academics.institution'),
        ),
        migrations.AddConstraint(
            model_name='inscription',
            constraint=models.UniqueConstraint(fields=('apprenant', 'annee_scolaire'), name='uniq_apprenant_par_annee'),
        ),
    ]
