# Generated by Django 5.1.6 on 2026-02-09 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0005_remove_classe_groupes_classe_groupes'),
        ('academics', '0006_remove_classe_apprenants_inscription_classe_and_more'),
    ]

    operations = [
    ]
