# Generated by Django 5.1.6 on 2026-02-11 11:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0006_remove_classe_apprenants_inscription_classe_and_more'),
        ('users', '0023_remove_apprenant_classe'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='inscription',
            name='uniq_apprenant_par_annee',
        ),
        migrations.AddField(
            model_name='classe',
            name='annee_scolaire',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='classes', to='academics.anneescolaire'),
        ),
        migrations.AddField(
            model_name='classe',
            name='institution',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='classes', to='academics.institution'),
        ),
        migrations.AddField(
            model_name='groupe',
            name='annee_scolaire',
            field=models.ForeignKey(blank=True, help_text='Année scolaire du groupe (optionnel mais recommandé)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='groupes', to='academics.anneescolaire'),
        ),
        migrations.AddField(
            model_name='groupe',
            name='institution',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='groupes', to='academics.institution'),
        ),
        migrations.AlterField(
            model_name='anneescolaire',
            name='date_debut',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='anneescolaire',
            name='date_fin',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='classe',
            name='filieres',
            field=models.ManyToManyField(blank=True, related_name='classes', to='academics.filiere'),
        ),
        migrations.AlterField(
            model_name='classe',
            name='groupes',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='classes', to='academics.groupe'),
        ),
        migrations.AlterField(
            model_name='classe',
            name='matieres',
            field=models.ManyToManyField(blank=True, related_name='classes', to='academics.matiere'),
        ),
        migrations.AlterField(
            model_name='groupe',
            name='enseignants',
            field=models.ManyToManyField(blank=True, related_name='academics_groupes', to='users.formateur'),
        ),
        migrations.AlterField(
            model_name='inscription',
            name='classe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inscriptions', to='academics.classe'),
        ),
        migrations.AlterField(
            model_name='institution',
            name='date_creation',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AddConstraint(
            model_name='classe',
            constraint=models.UniqueConstraint(fields=('nom', 'institution', 'annee_scolaire'), name='uniq_classe_par_inst_annee'),
        ),
        migrations.AddConstraint(
            model_name='groupe',
            constraint=models.UniqueConstraint(fields=('nom', 'institution', 'annee_scolaire'), name='uniq_groupe_par_inst_annee'),
        ),
        migrations.AddConstraint(
            model_name='inscription',
            constraint=models.UniqueConstraint(fields=('apprenant', 'institution', 'annee_scolaire'), name='uniq_inscription_inst_annee'),
        ),
    ]
