# Generated by Django 5.1.6 on 2026-02-09 14:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0007_merge_20260209_1421'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classe',
            name='groupes',
        ),
        migrations.AddField(
            model_name='classe',
            name='groupes',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='classe', to='academics.groupe'),
        ),
    ]
