# Generated by Django 5.1.6 on 2026-02-12 00:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0007_remove_inscription_uniq_apprenant_par_annee_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='domaineetude',
            options={'ordering': ['nom']},
        ),
        migrations.AlterModelOptions(
            name='filiere',
            options={'ordering': ['nom']},
        ),
        migrations.AlterModelOptions(
            name='matiere',
            options={'ordering': ['nom']},
        ),
        migrations.AddField(
            model_name='domaineetude',
            name='institution',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='domaines_etude', to='academics.institution'),
        ),
        migrations.AddField(
            model_name='filiere',
            name='institution',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='filieres', to='academics.institution'),
        ),
        migrations.AddField(
            model_name='matiere',
            name='institution',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='matieres', to='academics.institution'),
        ),
        migrations.AlterField(
            model_name='filiere',
            name='statut',
            field=models.CharField(choices=[('actif', 'Actif'), ('en_pause', 'En pause'), ('archive', 'Archivée')], default='actif', max_length=50),
        ),
        migrations.AlterUniqueTogether(
            name='domaineetude',
            unique_together={('institution', 'nom')},
        ),
        migrations.AlterUniqueTogether(
            name='filiere',
            unique_together={('institution', 'nom')},
        ),
        migrations.AlterUniqueTogether(
            name='matiere',
            unique_together={('institution', 'nom')},
        ),
    ]
