# Generated by Django 5.1.6 on 2026-02-12 00:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0008_alter_domaineetude_options_alter_filiere_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='specialite',
            options={'ordering': ['nom']},
        ),
        migrations.AddField(
            model_name='specialite',
            name='institution',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='specialites', to='academics.institution'),
        ),
        migrations.AlterUniqueTogether(
            name='specialite',
            unique_together={('institution', 'nom')},
        ),
    ]
