# Generated by Django 5.1.6 on 2026-02-12 00:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0009_alter_specialite_options_specialite_institution_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='anneescolaire',
            name='institution',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='annees_scolaires', related_query_name='annee_scolaire', to='academics.institution'),
        ),
        migrations.AlterField(
            model_name='specialite',
            name='institution',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='specialites', related_query_name='specialite', to='academics.institution'),
        ),
    ]
