# Generated by Django 5.1.6 on 2026-02-12 01:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0010_anneescolaire_institution_and_more'),
        ('users', '0026_alter_admin_options_alter_apprenant_options_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='groupe',
            name='uniq_groupe_par_inst_annee',
        ),
        migrations.AlterUniqueTogether(
            name='domaineetude',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='filiere',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='matiere',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='specialite',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='classe',
            name='groupes',
        ),
        migrations.AddField(
            model_name='anneescolaire',
            name='est_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='departement',
            name='date_debut_validite',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='departement',
            name='date_fin_validite',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='departement',
            name='est_actif',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='domaineetude',
            name='date_debut_validite',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='domaineetude',
            name='date_fin_validite',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='domaineetude',
            name='est_actif',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='filiere',
            name='date_debut_validite',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='filiere',
            name='date_fin_validite',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='filiere',
            name='est_actif',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='groupe',
            name='classe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='groupes', to='academics.classe'),
        ),
        migrations.AddField(
            model_name='matiere',
            name='date_debut_validite',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='matiere',
            name='date_fin_validite',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='matiere',
            name='est_actif',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='specialite',
            name='date_debut_validite',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='specialite',
            name='date_fin_validite',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='specialite',
            name='est_actif',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='anneescolaire',
            name='annee_format_classique',
            field=models.CharField(blank=True, help_text='Format classique (ex: 2025-2026)', max_length=9, null=True),
        ),
        migrations.AlterField(
            model_name='classe',
            name='date_creation',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='departement',
            name='institution',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='departements', to='academics.institution'),
        ),
        migrations.AlterField(
            model_name='filiere',
            name='date_creation',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='groupe',
            name='annee_scolaire',
            field=models.ForeignKey(blank=True, help_text='Année scolaire du groupe', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='groupes', to='academics.anneescolaire'),
        ),
        migrations.AlterField(
            model_name='inscription',
            name='annee_scolaire',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inscriptions', to='academics.anneescolaire'),
        ),
        migrations.AlterField(
            model_name='inscription',
            name='institution',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inscriptions', to='academics.institution'),
        ),
        migrations.AlterField(
            model_name='inscription',
            name='statut',
            field=models.CharField(choices=[('actif', 'Actif'), ('diplome', 'Diplômé'), ('retire', 'Retiré')], default='actif', max_length=20),
        ),
        migrations.AlterField(
            model_name='inscription',
            name='statut_paiement',
            field=models.CharField(choices=[('en_attente', 'En attente'), ('paye', 'Payé'), ('annule', 'Annulé')], default='en_attente', max_length=20),
        ),
        migrations.AddConstraint(
            model_name='anneescolaire',
            constraint=models.UniqueConstraint(fields=('institution', 'annee_format_classique'), name='uniq_annee_scolaire_par_institution'),
        ),
        migrations.AddConstraint(
            model_name='domaineetude',
            constraint=models.UniqueConstraint(fields=('institution', 'nom'), name='uniq_domaine_etude_par_institution'),
        ),
        migrations.AddConstraint(
            model_name='filiere',
            constraint=models.UniqueConstraint(fields=('institution', 'nom'), name='uniq_filiere_par_institution'),
        ),
        migrations.AddConstraint(
            model_name='groupe',
            constraint=models.UniqueConstraint(fields=('nom', 'institution', 'annee_scolaire', 'classe'), name='uniq_groupe_par_inst_annee_classe'),
        ),
        migrations.AddConstraint(
            model_name='matiere',
            constraint=models.UniqueConstraint(fields=('institution', 'nom'), name='uniq_matiere_par_institution'),
        ),
        migrations.AddConstraint(
            model_name='specialite',
            constraint=models.UniqueConstraint(fields=('institution', 'nom'), name='uniq_specialite_par_institution'),
        ),
    ]
