# Generated by Django 5.1.6 on 2026-02-12 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0008_remove_classe_groupes_classe_groupes'),
        ('academics', '0011_remove_groupe_uniq_groupe_par_inst_annee_and_more'),
    ]

    operations = [
    ]
