# Generated by Django 5.1.6 on 2026-02-12 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0012_merge_20260212_1727'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classe',
            name='groupes',
        ),
    ]
