# Generated by Django 5.1.6 on 2026-03-16 12:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0013_remove_classe_groupes'),
    ]

    operations = [
        migrations.AddField(
            model_name='domaineetude',
            name='departement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='domaines_etude', to='academics.departement'),
        ),
    ]
