# Generated by Django 5.1.6 on 2026-03-12 11:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0013_remove_classe_groupes'),
        ('notifications', '0003_alter_notification_options_notification_institution_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DigestNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frequence', models.CharField(choices=[('quotidien', 'Quotidien'), ('hebdomadaire', 'Hebdomadaire')], default='quotidien', max_length=15, verbose_name='Fréquence')),
                ('envoye', models.BooleanField(default=False, verbose_name='Envoyé')),
                ('envoye_le', models.DateTimeField(blank=True, null=True, verbose_name='Envoyé le')),
                ('periode_debut', models.DateTimeField(verbose_name='Début de la période')),
                ('periode_fin', models.DateTimeField(verbose_name='Fin de la période')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Digest de notifications',
                'verbose_name_plural': 'Digests de notifications',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PreferenceNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('activation_compte', 'Activation de compte'), ('reinitialisation_mdp', 'Réinitialisation de mot de passe'), ('compte_suspendu', 'Compte suspendu'), ('tentative_suspecte', 'Tentative suspecte sur compte'), ('inscription_cours', 'Inscription à un cours'), ('inscription_probleme', "Problème d'inscription"), ('creation_ressource', 'Nouvelle ressource académique'), ('modification_ressource', 'Ressource académique modifiée'), ('suppression_ressource', 'Ressource académique supprimée'), ('cours_cree', 'Cours créé'), ('cours_modifie', 'Cours modifié'), ('module_ajoute', 'Nouveau module ajouté'), ('sequence_ajoutee', 'Nouvelle séquence ajoutée'), ('ressource_pedagogique', 'Nouvelle ressource pédagogique'), ('contenu_publie', 'Contenu publié / modifié'), ('evaluation_publiee', 'Évaluation publiée'), ('evaluation_soumise', 'Évaluation soumise'), ('evaluation_corrigee', 'Résultat / Correction disponible'), ('copies_a_corriger', 'Copies à corriger'), ('rappel_evaluation', "Rappel d'évaluation imminente"), ('session_a_venir', 'Session à venir'), ('session_annulee', 'Session annulée'), ('session_deplacee', 'Session déplacée'), ('rappel_session', 'Rappel de session'), ('absence_enregistree', 'Absence enregistrée'), ('retard_enregistre', 'Retard enregistré'), ('absences_repetees', 'Absences répétées'), ('progression_faible', 'Alerte progression faible'), ('progression_anormale', 'Progression anormale détectée'), ('cours_termine', 'Cours terminé'), ('encouragement', 'Encouragement'), ('assignation_cours', 'Assignation à un cours / groupe'), ('changement_planning', "Changement d'emploi du temps"), ('paiement_du', 'Paiement / Échéance à venir'), ('paiement_rejete', 'Paiement rejeté'), ('facture_emise', 'Facture émise'), ('incident_securite', 'Incident de sécurité'), ('incident_systeme', 'Incident système majeur'), ('alerte_exploitation', "Alerte générale d'exploitation"), ('annonce_administrative', 'Annonce administrative')], max_length=50, verbose_name='Type de notification')),
                ('canal', models.CharField(choices=[('in_app', 'In-App'), ('email', 'Email'), ('push', 'Push mobile'), ('sms', 'SMS / WhatsApp')], max_length=10, verbose_name='Canal')),
                ('est_active', models.BooleanField(default=True, verbose_name='Activée')),
            ],
            options={
                'verbose_name': 'Préférence de notification',
                'verbose_name_plural': 'Préférences de notifications',
            },
        ),
        migrations.RemoveIndex(
            model_name='notification',
            name='notificatio_user_id_427e4b_idx',
        ),
        migrations.RemoveIndex(
            model_name='notification',
            name='notificatio_user_id_c62b26_idx',
        ),
        migrations.RenameField(
            model_name='notification',
            old_name='user',
            new_name='recipient',
        ),
        migrations.AddField(
            model_name='notification',
            name='action_url',
            field=models.CharField(blank=True, help_text="Route frontend vers l'entité concernée", max_length=500, null=True, verbose_name="URL d'action"),
        ),
        migrations.AddField(
            model_name='notification',
            name='annee_scolaire',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='academics.anneescolaire', verbose_name='Année scolaire'),
        ),
        migrations.AddField(
            model_name='notification',
            name='canal',
            field=models.CharField(choices=[('in_app', 'In-App'), ('email', 'Email'), ('push', 'Push mobile'), ('sms', 'SMS / WhatsApp')], default='in_app', max_length=10, verbose_name='Canal'),
        ),
        migrations.AddField(
            model_name='notification',
            name='entity_id',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name="ID de l'entité liée"),
        ),
        migrations.AddField(
            model_name='notification',
            name='entity_type',
            field=models.CharField(blank=True, choices=[('cours', 'Cours'), ('module', 'Module'), ('sequence', 'Séquence'), ('evaluation', 'Évaluation'), ('quiz', 'Quiz'), ('session', 'Session'), ('inscription', 'Inscription'), ('participation', 'Participation'), ('classe', 'Classe'), ('groupe', 'Groupe'), ('institution', 'Institution'), ('paiement', 'Paiement'), ('user', 'Utilisateur'), ('autre', 'Autre')], max_length=20, null=True, verbose_name="Type d'entité liée"),
        ),
        migrations.AddField(
            model_name='notification',
            name='expires_at',
            field=models.DateTimeField(blank=True, help_text='Passé cette date, la notification est considérée obsolète', null=True, verbose_name='Expire le'),
        ),
        migrations.AddField(
            model_name='notification',
            name='groupe_deduplication',
            field=models.CharField(blank=True, db_index=True, help_text="Ex: 'evaluation_soumise:42' — regroupe les notifs similaires", max_length=255, null=True, verbose_name='Clé de déduplication'),
        ),
        migrations.AddField(
            model_name='notification',
            name='metadata',
            field=models.JSONField(blank=True, default=dict, verbose_name='Métadonnées'),
        ),
        migrations.AddField(
            model_name='notification',
            name='nb_evenements_groupes',
            field=models.PositiveIntegerField(default=1, help_text="Nombre d'événements fusionnés dans cette notification", verbose_name='Événements groupés'),
        ),
        migrations.AddField(
            model_name='notification',
            name='priorite',
            field=models.CharField(choices=[('basse', 'Basse'), ('moyenne', 'Moyenne'), ('haute', 'Haute'), ('critique', 'Critique')], default='moyenne', max_length=10, verbose_name='Priorité'),
        ),
        migrations.AddField(
            model_name='notification',
            name='read_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Lu le'),
        ),
        migrations.AddField(
            model_name='notification',
            name='scheduled_at',
            field=models.DateTimeField(blank=True, help_text="Si renseigné, n'envoyer qu'à partir de cette date (Celery)", null=True, verbose_name='Programmée pour le'),
        ),
        migrations.AddField(
            model_name='notification',
            name='send_error',
            field=models.TextField(blank=True, verbose_name="Erreur d'envoi"),
        ),
        migrations.AddField(
            model_name='notification',
            name='sender',
            field=models.ForeignKey(blank=True, help_text='Null = notification système automatique', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications_envoyees', to=settings.AUTH_USER_MODEL, verbose_name='Expéditeur'),
        ),
        migrations.AddField(
            model_name='notification',
            name='sent_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Envoyé le'),
        ),
        migrations.AddField(
            model_name='notification',
            name='statut_envoi',
            field=models.CharField(choices=[('pending', 'En attente'), ('sent', 'Envoyé'), ('failed', 'Échec'), ('skipped', 'Ignoré')], default='pending', max_length=10, verbose_name="Statut d'envoi"),
        ),
        migrations.AddField(
            model_name='notification',
            name='titre',
            field=models.CharField(default='', max_length=255, verbose_name='Titre'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Créée le'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='institution',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='academics.institution', verbose_name='Institution'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='is_read',
            field=models.BooleanField(default=False, verbose_name='Lu'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='message',
            field=models.TextField(default='', verbose_name='Message'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('activation_compte', 'Activation de compte'), ('reinitialisation_mdp', 'Réinitialisation de mot de passe'), ('compte_suspendu', 'Compte suspendu'), ('tentative_suspecte', 'Tentative suspecte sur compte'), ('inscription_cours', 'Inscription à un cours'), ('inscription_probleme', "Problème d'inscription"), ('creation_ressource', 'Nouvelle ressource académique'), ('modification_ressource', 'Ressource académique modifiée'), ('suppression_ressource', 'Ressource académique supprimée'), ('cours_cree', 'Cours créé'), ('cours_modifie', 'Cours modifié'), ('module_ajoute', 'Nouveau module ajouté'), ('sequence_ajoutee', 'Nouvelle séquence ajoutée'), ('ressource_pedagogique', 'Nouvelle ressource pédagogique'), ('contenu_publie', 'Contenu publié / modifié'), ('evaluation_publiee', 'Évaluation publiée'), ('evaluation_soumise', 'Évaluation soumise'), ('evaluation_corrigee', 'Résultat / Correction disponible'), ('copies_a_corriger', 'Copies à corriger'), ('rappel_evaluation', "Rappel d'évaluation imminente"), ('session_a_venir', 'Session à venir'), ('session_annulee', 'Session annulée'), ('session_deplacee', 'Session déplacée'), ('rappel_session', 'Rappel de session'), ('absence_enregistree', 'Absence enregistrée'), ('retard_enregistre', 'Retard enregistré'), ('absences_repetees', 'Absences répétées'), ('progression_faible', 'Alerte progression faible'), ('progression_anormale', 'Progression anormale détectée'), ('cours_termine', 'Cours terminé'), ('encouragement', 'Encouragement'), ('assignation_cours', 'Assignation à un cours / groupe'), ('changement_planning', "Changement d'emploi du temps"), ('paiement_du', 'Paiement / Échéance à venir'), ('paiement_rejete', 'Paiement rejeté'), ('facture_emise', 'Facture émise'), ('incident_securite', 'Incident de sécurité'), ('incident_systeme', 'Incident système majeur'), ('alerte_exploitation', "Alerte générale d'exploitation"), ('annonce_administrative', 'Annonce administrative')], max_length=50, verbose_name='Type'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['recipient', '-created_at'], name='notificatio_recipie_a972ce_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['recipient', 'is_read'], name='notificatio_recipie_4e3567_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['type'], name='notificatio_type_ea918f_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['canal'], name='notificatio_canal_77cbd2_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['priorite'], name='notificatio_priorit_9af988_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['statut_envoi'], name='notificatio_statut__98dd03_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['entity_type', 'entity_id'], name='notificatio_entity__950da6_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['institution', '-created_at'], name='notificatio_institu_13d18c_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['scheduled_at'], name='notificatio_schedul_21ac35_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['expires_at'], name='notificatio_expires_4f3289_idx'),
        ),
        migrations.AddField(
            model_name='digestnotification',
            name='notifications',
            field=models.ManyToManyField(blank=True, related_name='digests', to='notifications.notification', verbose_name='Notifications regroupées'),
        ),
        migrations.AddField(
            model_name='digestnotification',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='digests', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur'),
        ),
        migrations.AddField(
            model_name='preferencenotification',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preferences_notifications', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur'),
        ),
        migrations.AddConstraint(
            model_name='preferencenotification',
            constraint=models.UniqueConstraint(fields=('user', 'type', 'canal'), name='uniq_preference_user_type_canal'),
        ),
    ]
