# Generated by Django 5.1.2 on 2024-11-17 17:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0002_initial'),
        ('resources', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ressourcesupplementaire',
            name='apprenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ressources_supplementaires', to='users.apprenant'),
        ),
        migrations.AddField(
            model_name='ressourcesupplementaire',
            name='sequence',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ressources_supplementaires', to='courses.sequence'),
        ),
        migrations.AddField(
            model_name='piecejointe',
            name='ressource_supplementaire',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pieces_jointes', to='resources.ressourcesupplementaire'),
        ),
        migrations.AddField(
            model_name='ressourcesupppiecejointe',
            name='piece_jointe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ressource_supp_piece_jointe', to='resources.piecejointe'),
        ),
        migrations.AddField(
            model_name='ressourcesupppiecejointe',
            name='ressource',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ressources_supplementaires_pieces_jointes', to='resources.ressourcesupplementaire'),
        ),
    ]
