# Generated by Django 5.1.6 on 2026-01-15 18:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0002_initial'),
        ('users', '0023_remove_apprenant_classe'),
    ]

    operations = [
        migrations.AddField(
            model_name='ressource',
            name='apprenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.apprenant'),
        ),
        migrations.AddField(
            model_name='ressource',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='ressource',
            name='est_supplementaire',
            field=models.BooleanField(default=False),
        ),
    ]
